/*
 * demolition man
 * capture_simon.c
 *
 * written by James Cardona
 *
 * Location Description:
 * mode started by claw switch capture_simon
 *
 * Scoring Description: (original game)
 * The ball is dropped down a tunnel and served to the
 * right ramp just like the Underground. The seven
 * major shots are lit for 5 mil each for three shots.
 * A 25 million award for completing all three shots for a total of 40 million

 * Scoring Description: (my rules)
 * same as above except:
 * major shots are lit for 15 mil each for three shots.
 * A 50 million award for completing all three shots for a total of 95 million.
 *
 * estimate of average capture simon mode score: 30 million to 95 million
 *
 */
/* CALLSET_SECTION (capture_simon, __machine3__) */

#include <freewpc.h>
#include "dm/global_constants.h"
#include "clawmagnet.h"
#include <diverter.h> //autogenerated by divhold.ct
#include "capture_simon.h"

//constants
const U8 			CAP_SIM_EASY_GOAL 	= 3;
const U8 			CAP_SIM_MED_GOAL 	= 4;
const U8 			CAP_SIM_HARD_GOAL 	= 5;
const U8 			CAP_SIM_GOAL_INCREMENT = 1;
const U8 			CAP_SIM_GOAL_MAX 	= 10;

//local variables
U8			capture_simon_SoundCounter;
U8 			capture_simon_mode_shots_made;
U8 			capture_simon_mode_shots_goal;
__local__ U8 			capture_simon_modes_achieved;
__local__ U8 			capture_simon_modes_completed;
U8			capture_simon_mode_timer;
score_t 	capture_simon_mode_score;
score_t 	capture_simon_mode_last_score;
score_t 	capture_simon_mode_next_score;
score_t 	capture_simon_mode_score_total_score;


//external variables

//internally called function prototypes  --external found at protos.h
void capture_simon_reset (void);
void capture_simon_player_reset (void);
void capture_simon_effect_deff(void);
void capture_simon_mode_init (void);
void capture_simon_mode_expire (void);
void capture_simon_mode_exit (void);
void cap_simon_choose_random_flag_set(void);

/****************************************************************************
 * mode definition structure
 ***************************************************************************/
struct timed_mode_ops capture_simon_mode = {
	DEFAULT_MODE,
	.init = capture_simon_mode_init,
	.exit = capture_simon_mode_expire,
	.gid = GID_CAPTURE_SIMON_MODE_RUNNING,
	.music = MUS_MD_CAPTURE_SIMON,
	.deff_starting = DEFF_CAPTURE_SIMON_START_EFFECT,
	.deff_running = DEFF_CAPTURE_SIMON_EFFECT,
	.deff_ending = DEFF_CAPTURE_SIMON_END_EFFECT,
	.prio = PRI_GAME_MODE4,
	.init_timer = 48,
	.timer = &capture_simon_mode_timer,
	.grace_timer = 2,
//	.pause = system_timer_pause,
};



/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void capture_simon_reset (void) {
	flag_off (FLAG_IS_CAPSIM_SIDERAMP_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_LEFTRAMP_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_RIGHTRAMP_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_UNDER_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_CENTERRAMP_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_LEFTORB_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_RIGHTORB_ACTIVATED);
	flag_off (FLAG_CAPTURE_SIMON_INITIALSTART);
}//end of function


void capture_simon_player_reset (void) {
	capture_simon_reset();
	capture_simon_modes_achieved = 0;
	capture_simon_modes_completed = 0;//these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	capture_simon_mode_shots_made = 0;
	capture_simon_mode_shots_goal = CAP_SIM_EASY_GOAL;
	score_zero(capture_simon_mode_score_total_score);
	capture_simon_SoundCounter = 0;
}//end of function



//purpose here is to prevent underground from triggering since
//this shot feeds to underground
void capture_simon_startup_task (void) {
	flag_on(FLAG_CAPTURE_SIMON_INITIALSTART);
	task_sleep_sec(10);
	//this is just here in case deff hangs or does not play
	flag_off (FLAG_CAPTURE_SIMON_INITIALSTART);
	task_exit();
}//end of function




void capture_simon_mode_init (void) {
	task_create_gid1(GID_CAP_SIM_START, capture_simon_startup_task);
	//the claw mode can expire on its own and since it is a lower priority it will not display
			//callset_invoke (end_claw_mode); // as this seemed to cause occasional crashes
			clawmagnet_off ();
			flag_off(FLAG_IS_BALL_ON_CLAW);
			flipper_enable ();
			ballsave_add_time (10);
	capture_simon_mode_shots_made = 0;
	++capture_simon_modes_achieved;
	kill_combos ();
	//flash lamp for a time
	lamp_tristate_flash(LM_CLAW_CAPTURE_SIMON);
	task_sleep(TIME_500MS);
	lamp_tristate_on(LM_CLAW_CAPTURE_SIMON);
	score_zero(capture_simon_mode_score);
	score_zero(capture_simon_mode_last_score);
	score_zero(capture_simon_mode_next_score);
	switch (capture_simon_modes_achieved ){
		case 1: score_add(capture_simon_mode_next_score, score_table[CAPSIM_HIT_SCORE_1]); break;
		case 2: score_add(capture_simon_mode_next_score, score_table[CAPSIM_HIT_SCORE_2]); break;
		default:
		case 3: score_add(capture_simon_mode_next_score, score_table[CAPSIM_HIT_SCORE_3]); break;
	}//end of switch
	//this pause is here to give sounds time to finish
	task_sleep(TIME_500MS);
	task_sleep(TIME_500MS);
	task_sleep(TIME_500MS);
	cap_simon_choose_random_flag_set();
	all_arrow_update();
	demotime_increment();
	diverter_stop();//defined in divhold2.ct
	task_kill_gid (GID_CR_LIGHTS);
}//end of function




//this is an exit on timeout, ball still in play
void capture_simon_mode_expire (void) {
	flag_off (FLAG_IS_CAPSIM_SIDERAMP_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_LEFTRAMP_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_RIGHTRAMP_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_UNDER_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_CENTERRAMP_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_LEFTORB_ACTIVATED);
	flag_off (FLAG_IS_CAPSIM_RIGHTORB_ACTIVATED);
	all_arrow_update();
	flag_off (FLAG_CAPTURE_SIMON_INITIALSTART);

	diverter_check();

	capture_simon_mode_shots_goal += CAP_SIM_GOAL_INCREMENT;//increment goal for next time

	combo_init ();
}//end of function



//this is an exit on end of ball
//must do this differently to prevent excessive cycling of diverter which
//tends to blow fuses
void capture_simon_mode_exit (void) {
		flag_off (FLAG_IS_CAPSIM_SIDERAMP_ACTIVATED);
		flag_off (FLAG_IS_CAPSIM_LEFTRAMP_ACTIVATED);
		flag_off (FLAG_IS_CAPSIM_RIGHTRAMP_ACTIVATED);
		flag_off (FLAG_IS_CAPSIM_UNDER_ACTIVATED);
		flag_off (FLAG_IS_CAPSIM_CENTERRAMP_ACTIVATED);
		flag_off (FLAG_IS_CAPSIM_LEFTORB_ACTIVATED);
		flag_off (FLAG_IS_CAPSIM_RIGHTORB_ACTIVATED);
		all_arrow_update();
		flag_off (FLAG_CAPTURE_SIMON_INITIALSTART);

		capture_simon_mode_shots_goal += CAP_SIM_GOAL_INCREMENT;//increment goal for next time

		timed_mode_end2 (&capture_simon_mode);
	}//end of function



/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (capture_simon, music_refresh)  	{ timed_mode_music_refresh (&capture_simon_mode); }
CALLSET_ENTRY (capture_simon, end_ball) 		{ if (timed_mode_running_p(&capture_simon_mode) ) capture_simon_mode_exit(); }
CALLSET_ENTRY (capture_simon, display_update) 	{ timed_mode_display_update (&capture_simon_mode); }

CALLSET_ENTRY (capture_simon, start_player) 	{ capture_simon_player_reset(); }
CALLSET_ENTRY (capture_simon, start_ball) 		{ capture_simon_reset(); }



/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
CALLSET_ENTRY (capture_simon, sw_claw_capture_simon) {
	demotime_increment();
	timed_mode_begin (&capture_simon_mode);//start mode
}//end of function



 //center ramp shot made during capture_simon mode
void capture_simon_made(void) {
	++capture_simon_mode_shots_made;
	score_zero(capture_simon_mode_last_score);
	switch (capture_simon_modes_achieved ){
		case 1:
			score (CAPSIM_HIT_SCORE_1);
			score_add(capture_simon_mode_last_score, score_table[CAPSIM_HIT_SCORE_1]);
			break;
		case 2:
			//2nd time we are in capture_simon - score differently
			score (CAPSIM_HIT_SCORE_2);
			score_add(capture_simon_mode_last_score, score_table[CAPSIM_HIT_SCORE_2]);
			break;
		default:
		case 3:
			//3rd time we are in capture_simon - score differently
			score (CAPSIM_HIT_SCORE_3);
			score_add(capture_simon_mode_last_score, score_table[CAPSIM_HIT_SCORE_3]);
			break;
	}//end of switch
	score_add (capture_simon_mode_score, capture_simon_mode_last_score);
	score_add (capture_simon_mode_score_total_score, capture_simon_mode_last_score);

	if (capture_simon_mode_shots_made < capture_simon_mode_shots_goal ) {
			cap_simon_choose_random_flag_set();
			all_arrow_update();
			deff_start (DEFF_CAPTURE_SIMON_HIT_EFFECT);

	}	//IF FINAL CAPTURE SIMON SHOT MADE
	else {
		score (CAP_SIM_COMPLETED_SCORE);
		score_add(capture_simon_mode_score, score_table[CAP_SIM_COMPLETED_SCORE]);
		score_add (capture_simon_mode_score_total_score, score_table[CAP_SIM_COMPLETED_SCORE]);
		deff_start (DEFF_CAPTURE_SIMON_END_EFFECT);
		capture_simon_mode_exit();
		}
}//end of function



/****************************************************************************
 *
 * DMD display and sound effects
 *
 ****************************************************************************/
void cap_sim_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void capture_simon_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




U8 			capture_simon_MessageCounter;
void capture_simon_start_effect_deff(void) {
	capture_simon_MessageCounter = random_scaled(2);
	if (++capture_simon_MessageCounter > 1) 	capture_simon_MessageCounter = 0; //for testing

	dmd_clean_page_high ();//
	dmd_clean_page_low ();//

	sound_start (ST_SPEECH, SPCH_UNDER_ARREST, SL_3S, PRI_GAME_QUICK1);

	switch (capture_simon_MessageCounter) {
		default:
		case 0:
			cap_sim_animation_display_effect (IMG_CAPSIMON_A_START, IMG_CAPSIMON_A_END);
			capture_simon_frame_bitfade_fast(IMG_SIMON_B_START);

			sound_start (ST_SPEECH, SPCH_SO_SCARED, SL_4S, PRI_GAME_QUICK1);

			cap_sim_animation_display_effect (IMG_SIMON_B_START, IMG_SIMON_B_END);
			dmd_map_overlay ();
			dmd_clean_page_low ();
			font_render_string_center (&font_bitoutline, DMD_MIDDLE_X - 20, DMD_BIG_CY_Top, "CAPTURE");
			font_render_string_center (&font_bitoutline, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "SIMON");
			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(IMG_SIMON_B_END);
			dmd_overlay_outline ();
			dmd_show2 ();
			break;
		case 1:
			cap_sim_animation_display_effect (IMG_SIMON_B_START, IMG_SIMON_B_END);
			capture_simon_frame_bitfade_fast(IMG_CAPSIMON_A_START);

			sound_start (ST_SPEECH, SPCH_SO_SCARED, SL_4S, PRI_GAME_QUICK1);

			cap_sim_animation_display_effect (IMG_CAPSIMON_A_START, IMG_CAPSIMON_A_END);
			dmd_map_overlay ();
			dmd_clean_page_low ();
			font_render_string_center (&font_bitoutline, DMD_MIDDLE_X - 20, DMD_BIG_CY_Top, "CAPTURE");
			font_render_string_center (&font_bitoutline, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "SIMON");
			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(IMG_CAPSIMON_A_END);
			dmd_overlay_outline ();
			dmd_show2 ();
			break;
	}//end of switch
	task_sleep_sec (1);
	flag_off (FLAG_CAPTURE_SIMON_INITIALSTART);
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff



void capture_simon_hit_effect_deff(void) {
	//capture_simon_mode_shots_made++; //for testing only
	dmd_alloc_low_clean ();
	U8 cap_simon_effect_randomizer = random_scaled(2);
	switch (cap_simon_effect_randomizer) {
	case 0 :
			//	DRAW HAND CUFFS
				sound_start (ST_SPEECH, SPCH_WES_LAUGH1, SL_4S, PRI_GAME_QUICK5);
				bitmap_blit (cuffs_1_bits, 0, 0);
				font_render_string_center (&font_bitoutline, DMD_MIDDLE_X + 20, DMD_BIG_CY_Top, "CAUGHT");
				sprintf_score (capture_simon_mode_last_score);
				font_render_string_center (&font_bitoutline, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, sprintf_buffer);
				dmd_show_low ();
				task_sleep_sec (2);
			//	DRAW FOOT STEPS RUNNING AWAY
				dmd_clean_page_low ();
				bitmap_blit (footstep_left_2_bits, 104, 18);
				dmd_show_low ();
				sound_start (ST_EFFECT, TOINK1, SL_1S, PRI_GAME_QUICK5);
				task_sleep (TIME_200MS);
				bitmap_blit (footstep_left_1_bits, 76, 6);
				sound_start (ST_EFFECT, TOINK2, SL_1S, PRI_GAME_QUICK5);
				dmd_show_low ();
				task_sleep (TIME_200MS);
					bitmap_blit (footstep_left_2_bits, 48, 18);
					dmd_show_low ();
					sound_start (ST_EFFECT, TOINK1, SL_1S, PRI_GAME_QUICK5);
					task_sleep (TIME_200MS);
					bitmap_blit (footstep_left_1_bits, 20, 6);
					sound_start (ST_EFFECT, TOINK2, SL_1S, PRI_GAME_QUICK5);
					task_sleep (TIME_200MS);
					dmd_show_low ();
				task_sleep_sec (1);
		break;
	case 1 :
				//	DRAW HAND CUFFS
					sound_start (ST_SPEECH, SPCH_WES_LAUGH2, SL_4S, PRI_GAME_QUICK5);
					bitmap_blit (cuffs_3_bits, 0, 10);
					font_render_string_center (&font_bitoutline, DMD_MIDDLE_X + 20, DMD_BIG_CY_Top, "CAUGHT");
					sprintf_score (capture_simon_mode_last_score);
					font_render_string_center (&font_bitoutline, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, sprintf_buffer);
					dmd_show_low ();
					task_sleep_sec (2);
				//	DRAW FOOT STEPS RUNNING AWAY
					dmd_clean_page_low ();
					bitmap_blit (footstep_right_2_bits, 0, 18);
					dmd_show_low ();
					sound_start (ST_EFFECT, TOINK1, SL_1S, PRI_GAME_QUICK5);
					task_sleep (TIME_200MS);
					bitmap_blit (footstep_right_1_bits, 28, 6);
					sound_start (ST_EFFECT, TOINK2, SL_1S, PRI_GAME_QUICK5);
					dmd_show_low ();
					task_sleep (TIME_200MS);
							bitmap_blit (footstep_right_2_bits, 56, 18);
							dmd_show_low ();
							sound_start (ST_EFFECT, TOINK1, SL_1S, PRI_GAME_QUICK5);
							task_sleep (TIME_200MS);
							bitmap_blit (footstep_right_1_bits, 84, 6);
							sound_start (ST_EFFECT, TOINK2, SL_1S, PRI_GAME_QUICK5);
							dmd_show_low ();
							task_sleep (TIME_200MS);
					task_sleep_sec (1);
			break;
	}//end of switch
	deff_exit ();
}//end of mode_effect_deff





void capture_simon_end_effect_deff(void) {
	//capture_simon_mode_shots_made++; //for testing only
	dmd_alloc_low_clean ();
	sound_start (ST_SPEECH, SPCH_UNDER_ARREST, SL_3S, PRI_GAME_QUICK1);
			//	DRAW HAND CUFFS
				bitmap_blit (cuffs_3_bits, 0, 0);
				font_render_string_center (&font_bitoutline, DMD_MIDDLE_X + 20, DMD_BIG_CY_Top, "CAUGHT");
				sprintf_score (capture_simon_mode_score);
				font_render_string_center (&font_bitoutline, DMD_MIDDLE_X + 10, DMD_BIG_CY_Bot, sprintf_buffer);
				dmd_show_low ();
				task_sleep_sec (2);
	deff_exit ();
}//end of mode_effect_deff





void capture_simon_effect_deff(void) {
	U8 i = 0;
	U8 j = 0;
	__boolean TOGGLE = FALSE;
	__boolean TOGGLE_BOTTOM = FALSE;

	for (;;) {
		dmd_alloc_pair_clean();

		dmd_draw_thin_border (dmd_low_buffer);

		if (++i % 10 == 0) { if (TOGGLE) TOGGLE = FALSE; else TOGGLE = TRUE; }//change TOGGLE once per second

		if (i % 10 != 0) { //draw for 4/5 and blank for 1/5
					if (TOGGLE) {
						font_render_string_center (&font_bitoutline, DMD_MIDDLE_X + 23, DMD_BIG_CY_Top - 3, "SIMON");
							}//end of if (TOGGLE)
					else {
						font_render_string_center (&font_bitoutline, DMD_MIDDLE_X + 23, DMD_BIG_CY_Top - 3, "CAPTURE");
						}//end of else
		}//end of if (i % 5 != 0)

		if (++j % 40 == 0) { if (TOGGLE_BOTTOM) TOGGLE_BOTTOM = FALSE; else TOGGLE_BOTTOM = TRUE; }//change TOGGLE once per second

		if (j % 40 != 0) { //draw for 9/10 and blank for 1/10
					if (TOGGLE_BOTTOM) {
						sprintf ("%d SEC,  %d HIT", capture_simon_mode_timer, capture_simon_mode_shots_made);
						font_render_string_center (&font_var5, DMD_MIDDLE_X + 23, DMD_SMALL_CY_3, sprintf_buffer);

						sprintf_score (capture_simon_mode_next_score);
						font_render_string_center (&font_term6, DMD_MIDDLE_X + 23, DMD_MED_CY_3, sprintf_buffer);
						bitmap_blit (cuffs_1_bits, 0, 1);
							}//end of if (TOGGLE)
					else {
						sprintf ("SHOOT");
						font_render_string_center (&font_term6, DMD_MIDDLE_X + 25, DMD_MED_CY_2, sprintf_buffer);
						sprintf ("ARROWS");
						font_render_string_center (&font_term6, DMD_MIDDLE_X + 25, DMD_MED_CY_3, sprintf_buffer);
						bitmap_blit (cuffs_3_bits, 0, 1);
						}//end of else
		}//end of if (i % 10 != 0)

		dmd_show_low ();
		task_sleep (TIME_200MS);
	}//END OF ENDLESS LOOP
}//end of mode_effect_deff





/****************************************************************************
 *
 * randomize flag chosen
 *
 * we are using a very stupid and in-elegant
 * way of randomness - basically, we have a number
 * of predefined sets of flags and we randomly
 * pick one of those sets
 ****************************************************************************/
void cap_simon_choose_random_flag_set(void) {
	U8 random_chooser;
	random_chooser = random_scaled(5);
	switch (random_chooser) {
	case 0:
		flag_on 	(FLAG_IS_CAPSIM_SIDERAMP_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_LEFTRAMP_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_RIGHTRAMP_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_UNDER_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_CENTERRAMP_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_LEFTORB_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_RIGHTORB_ACTIVATED);
		break;
	case 1:
		flag_on 	(FLAG_IS_CAPSIM_SIDERAMP_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_LEFTRAMP_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_RIGHTRAMP_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_UNDER_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_CENTERRAMP_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_LEFTORB_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_RIGHTORB_ACTIVATED);
		break;
	case 2:
		flag_off 	(FLAG_IS_CAPSIM_SIDERAMP_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_LEFTRAMP_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_RIGHTRAMP_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_UNDER_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_CENTERRAMP_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_LEFTORB_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_RIGHTORB_ACTIVATED);
		break;
	case 3:
		flag_off 	(FLAG_IS_CAPSIM_SIDERAMP_ACTIVATED);
		flag_off	(FLAG_IS_CAPSIM_LEFTRAMP_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_RIGHTRAMP_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_UNDER_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_CENTERRAMP_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_LEFTORB_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_RIGHTORB_ACTIVATED);
		break;
	case 4:
		flag_on 	(FLAG_IS_CAPSIM_SIDERAMP_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_LEFTRAMP_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_RIGHTRAMP_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_UNDER_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_CENTERRAMP_ACTIVATED);
		flag_on 	(FLAG_IS_CAPSIM_LEFTORB_ACTIVATED);
		flag_off 	(FLAG_IS_CAPSIM_RIGHTORB_ACTIVATED);
		break;
	}//end of switch
}//end of function

