/*
 * demolition man
 * car_chase_mode.c
 *
 * written by James Cardona
 *
 * Location Description:
 * Located to the left and above the retina scan is the Car Crash target.
 * the Car Crash contains two captive cars (yes, that's right ... captive cars) behind the impact target.
 * Triggering the switch causes two miniature cars to crash.
 * The ball will rocket off this target, but there's a ballsaver if it goes STDM.
 *
 * Scoring Description: (original game)
 * Hitting the target with three lights lit award the Car Crash.
 * Car Crash lights Car Chase on the left/right lamps.
 *
 * Scoring Description: (my rules)
 * same as above except:
 * car chase is not a single lit ramp after a car crash hit but an entire mode
 * The car chase mode is lit after a predefined number of car crashes where the second car makes the switch.  Then
 * the mode starts and lights both ramps for car chases.  The car chase stays lit until ball drain
 * or until car crash is hit.  Car chase ramps score 15 million per shot.
 *
 * estimate of average carcrash mode score: 45 million to 90 million
 *
 */
/* CALLSET_SECTION (car_chase_mode, __machine2__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct

//constants
const U8 	car_chase_TotalNumOfSounds = 11; //num between 0 and N-1 == N total
const sound_code_t car_chase_SoundsArray[] = {	SPCH_STOP_THIS,		SPCH_OHH_YEAH3,				SPCH_LETS_GO1,
												SPCH_YEEAHHAA,		SPCH_WOOH, 					SPCH_WOW,
												SPCH_PUNCH_IT, 		SPCH_PUSH_PEDAL_HARD,		SPCH_GO_LEFT,
												SPCH_CATCH_UP, 		SPCH_STEP_ON_IT};


//local variables
__local__ U8 			car_chase_modes_achieved;
U8 			car_chase_mode_shots_made;
U8			car_chase_mode_timer;
U8			carchase_MessageCounter;
score_t 	car_chase_mode_score;
score_t 	car_chase_mode_temp_score;
score_t 	car_chase_mode_score_total_score;


//external variables

//internally called function prototypes  --external found at protos.h
void car_chase_reset (void);
void car_chase_player_reset (void);
void car_chase_mode_init (void);
void car_chase_mode_expire (void);
void car_chase_mode_exit (void);


/****************************************************************************
 * mode definition structure
 ***************************************************************************/
struct timed_mode_ops car_chase_mode = {
	DEFAULT_MODE,
	.init = car_chase_mode_init,
	.exit = car_chase_mode_expire,
	.gid = GID_CAR_CHASE_MODE_RUNNING,
	.music = MUS_MD_CAR_CRASH,
	.deff_starting = DEFF_CAR_CHASE_START_EFFECT,
	.deff_running = DEFF_CAR_CHASE_EFFECT,
//	.deff_ending = DEFF_CAR_CHASE_END_EFFECT,
	.prio = PRI_GAME_MODE1,
	.init_timer = 33,
	.timer = &car_chase_mode_timer,
	.grace_timer = 2,
//	.pause = system_timer_pause,
};



/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void car_chase_reset (void) {
	flag_off (FLAG_IS_CARCHASE_MODE_RUNNING);
}//end of function



void car_chase_player_reset (void) {
	car_chase_reset();
	car_chase_modes_achieved = 0;
	car_chase_mode_shots_made = 0;
	score_zero(car_chase_mode_score_total_score);
	carchase_MessageCounter = 0;
}//end of function



void car_chase_mode_init (void) {
	car_chase_mode_shots_made = 0;
	flag_on (FLAG_IS_CARCHASE_MODE_RUNNING);
	ballsave_add_time (10);
	++car_chase_modes_achieved;
	diverter_stop();//defined in divhold2.ct
	task_kill_gid (GID_CR_LIGHTS);
	carchase_mode_on(); //at ramps.c
	serve_ball_auto(); //add one ball to the playfield - NOT a multiball since doesn't change global ball count
	sound_start (ST_SPEECH, SPCH_WUSS_SPARTAN, SL_4S, PRI_GAME_QUICK5);
	task_sleep_sec (2);
	sound_start (ST_SPEECH, SPCH_EXCUSE_ME, SL_4S, PRI_GAME_QUICK5);
	task_sleep_sec (1);
	sound_start (ST_SPEECH, SPCH_BETWEEN_YOU_N_ME, SL_4S, PRI_GAME_QUICK5);
	//flash lamp for a time
	score_zero(car_chase_mode_score);

	lamp_tristate_off (LM_CLAW_READY);
}//end of function



//this is an exit on timeout, ball still in play
void car_chase_mode_expire (void) {
	carchase_mode_off(); //at ramps.c
	flag_off (FLAG_IS_CARCHASE_MODE_RUNNING);
	diverter_check();
}//end of function





//this is an exit on end of ball
//must do this differently to prevent excessive cycling of diverter which
//tends to blow fuses
void car_chase_mode_exit (void) {
	carchase_mode_off(); //at ramps.c
	flag_off (FLAG_IS_CARCHASE_MODE_RUNNING);

	timed_mode_end2(&car_chase_mode);
}//end of function




/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (car_chase, music_refresh)  	{ timed_mode_music_refresh (&car_chase_mode); }
CALLSET_ENTRY (car_chase, end_ball) 		{ if (timed_mode_running_p(&car_chase_mode) ) car_chase_mode_exit(); }
CALLSET_ENTRY (car_chase, display_update) 	{ timed_mode_display_update (&car_chase_mode); }

CALLSET_ENTRY (car_chase, start_player) 	{ car_chase_player_reset(); }
CALLSET_ENTRY (car_chase, start_ball) 		{ car_chase_reset(); }




/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
//this is called from car_crash.c
void start_car_chase(void) {
	timed_mode_begin (&car_chase_mode);//start mode
}//end of function


void car_chase_ramp_made(void) {
	++car_chase_mode_shots_made;

	deff_start (DEFF_CAR_CHASE_HIT_EFFECT);

	score_zero(car_chase_mode_temp_score);
	switch (car_chase_modes_achieved ){
		case 1:
			score (CARCHASE_HIT_SCORE_1);
			score_add(car_chase_mode_temp_score, score_table[CARCHASE_HIT_SCORE_1]);
			break;
		case 2: //2nd time we are in car_chase - score differently
			score (CARCHASE_HIT_SCORE_2);
			score_add(car_chase_mode_temp_score, score_table[CARCHASE_HIT_SCORE_2]);
			break;
		default: //all cases past 3rd time we are in car_chase
		case 3: //3rd time we are in car_chase - score differently
			score (CARCHASE_HIT_SCORE_3);
			score_add(car_chase_mode_temp_score, score_table[CARCHASE_HIT_SCORE_3]);
			break;
	}//end of switch
	score_add (car_chase_mode_score, car_chase_mode_temp_score);
	score_add (car_chase_mode_score_total_score, car_chase_mode_temp_score);
}//end of function




/****************************************************************************
 *
 * DMD display and sound effects
 *
 ****************************************************************************/
void car_chase_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	dmd_alloc_pair_clean ();// Clean both pages
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void car_chase_animation_display_effect_w_words (U16 start_frame, U16 end_frame){
	U16 fno;
	dmd_alloc_pair_clean ();// Clean both pages
	for (fno = start_frame; fno <= end_frame; fno += 2) {
			dmd_map_overlay ();
			dmd_clean_page_low ();
			font_render_string_center (&font_fipps, DMD_MIDDLE_X - 20, DMD_BIG_CY_Top, "CAR_CHASE");
			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(fno);
			dmd_overlay_outline ();
			dmd_show2 ();
			task_sleep (TIME_100MS);
	}//end of inner loop
}//end of mode_effect_deff




void car_chase_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}//end of mode_effect_deff




void car_frame_with_words_display_fipps_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_fipps, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);
}//end of mode_effect_deff




void car_chase_start_effect_deff(void) {
	sound_start (ST_SAMPLE, CAR_SKID, SL_2S, PRI_GAME_QUICK5);

	car_chase_animation_display_effect (IMG_CARCHASE_A_START, IMG_CARCHASE_A_END);
	car_chase_animation_display_effect (IMG_CARCHASE_B_START, IMG_CARCHASE_B_END);
	car_chase_animation_display_effect (IMG_CARCHASE_C_START, IMG_CARCHASE_C_END);
	car_chase_animation_display_effect (IMG_CARCHASE_D_START, IMG_CARCHASE_D_END);

	dmd_sched_transition (&trans_scroll_left_fast);
	dmd_alloc_low_clean ();

	sound_start (ST_SAMPLE, CAR_SKID, SL_2S, PRI_GAME_QUICK5);

	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Cent, "SHOOT RAMPS");
	dmd_show_low ();
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff




void car_chase_hit_effect_deff(void) {
	U8 car_chase_SoundCounter;
	car_chase_SoundCounter = random_scaled(car_chase_TotalNumOfSounds);//from kernal/random.c
	dmd_clean_page_high ();//
	dmd_clean_page_low ();//

	//NOTE: skid sound is played on ramp enter at ramps.c
	//these sounds are on ramp exit
	sound_start (ST_SPEECH, car_chase_SoundsArray[car_chase_SoundCounter], SL_4S, PRI_GAME_QUICK2);
	sound_start (ST_EFFECT, CAR_GEAR_CHANGE, SL_2S, PRI_GAME_QUICK2);

	if (IN_TEST) {	if (++carchase_MessageCounter > 8) carchase_MessageCounter = 0; }
	else			carchase_MessageCounter = random_scaled(9);


	switch (carchase_MessageCounter) {
		default:
		case 0:
			car_chase_animation_display_effect (IMG_CARCHASE_B_START, IMG_CARCHASE_B_END);
			car_chase_animation_display_effect (IMG_CARCHASE_A_START, IMG_CARCHASE_A_END);
			break;
		case 1:
			car_chase_animation_display_effect (IMG_CARCHASE_C_START, IMG_CARCHASE_C_END);
			car_chase_animation_display_effect (IMG_CARCHASE_B_START, IMG_CARCHASE_B_END);
			break;
		case 2:
			car_chase_animation_display_effect (IMG_CARCHASE_D_START, IMG_CARCHASE_D_END);
			car_chase_animation_display_effect (IMG_CARCHASE_C_START, IMG_CARCHASE_C_END);
			break;
		case 3:
			car_chase_animation_display_effect (IMG_CARCHASE_H_START, IMG_CARCHASE_H_END);
			car_chase_animation_display_effect (IMG_CARCHASE_D_START, IMG_CARCHASE_D_END);
			break;
		case 4:
			car_chase_animation_display_effect (IMG_CARCHASE_F1_START, IMG_CARCHASE_F1_END);
			car_chase_animation_display_effect (IMG_CARCHASE_E_START, IMG_CARCHASE_E_END);
			break;
		case 5:
			car_chase_animation_display_effect (IMG_CARCHASE_F2_START, IMG_CARCHASE_F2_END);
			car_chase_animation_display_effect (IMG_CARCHASE_H_START, IMG_CARCHASE_H_END);
			break;
		case 6:
			car_chase_animation_display_effect (IMG_CARCHASE_F2_START, IMG_CARCHASE_F2_END);
			car_chase_animation_display_effect (IMG_CARCHASE_F1_START, IMG_CARCHASE_F1_END);
			break;
		case 7:
			car_chase_animation_display_effect (IMG_CARCHASE_A_START, IMG_CARCHASE_A_END);
			car_chase_animation_display_effect (IMG_CARCHASE_J_START, IMG_CARCHASE_J_END);
			break;
		case 8:
			car_chase_animation_display_effect (IMG_CARCHASE_J_START, IMG_CARCHASE_J_END);
			car_chase_animation_display_effect (IMG_CARCHASE_E_START, IMG_CARCHASE_E_END);
			break;
		}//end of switch
	task_sleep (TIME_100MS);
	deff_exit ();
}//end of function



void car_chase_effect_deff(void) {
	U8 i = 0;
	for (;;) {
		if (++i % 5 == 0) 	{
			sound_start (ST_SAMPLE, CAR_SKID, SL_2S, PRI_GAME_QUICK5);
			dmd_sched_transition (&trans_scroll_left_fast);
		}
		dmd_alloc_low_clean ();
		font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Top, "CAR_CHASE");
		sprintf ("%d SEC LEFT,  %d HIT", car_chase_mode_timer, car_chase_mode_shots_made);
		font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_3, sprintf_buffer);
		sprintf_score (car_chase_mode_score);
		font_render_string_center (&font_term6, DMD_MIDDLE_X, DMD_MED_CY_3, sprintf_buffer);
		dmd_show_low ();
		task_sleep (TIME_500MS);
	}//END OF ENDLESS LOOP
}//end of mode_effect_deff





void car_chase_end_effect_deff(void) {
	dmd_alloc_low_clean ();
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Top, "CAR_CHASE");
	sprintf("COMPLETE");
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Bot, sprintf_buffer);
	dmd_show_low ();
	task_sleep_sec (2);
	deff_exit ();
	}//end of mode_effect_deff

