/*
 * demolition man
 * car_chase_mode.c
 *
 * written by James Cardona
 *
 * Location Description:
 * Located to the left and above the retina scan is the Car Crash target.
 * the Car Crash contains two captive cars (yes, that's right ... captive cars) behind the impact target.
 * Triggering the switch causes two miniature cars to crash.
 * The ball will rocket off this target, but there's a ballsaver if it goes STDM.
 *
 * Scoring Description: (original game)
 * Hitting the target with three lights lit award the Car Crash.
 * Car Crash lights Car Chase on the left/right lamps.
 *
 * Scoring Description: (my rules)
 * same as above except:
 * car chase is not a single lit ramp after a car crash hit but an entire mode
 * The car chase mode is lit after a predefined number of car crashes where the second car makes the switch.  Then
 * the mode starts and lights both ramps for car chases.  The car chase stays lit until ball drain
 * or until car crash is hit.  Car chase ramps score 15 million per shot.
 *
 * estimate of average carcrash mode score: 45 million to 90 million
 *
 */
/* CALLSET_SECTION (car_chase_mode, __machine2__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include "car_chase.h"
#include <diverter.h> //autogenerated by divhold.ct

//constants
const U8 	car_chase_TotalNumOfSounds = 8; //num between 0 and N-1 == N total
const sound_code_t car_chase_SoundsArray[] = {	SPCH_WHAT_ARE_YOU_DOING, 	SPCH_STOP_THIS, 		SPCH_WEEAHOO,
												SPCH_OHH_YEAH3,				SPCH_LETS_GO1, 			SPCH_YEEAHHAA,
												SPCH_WOOH, 					SPCH_WOW };

//local variables
U8 			car_chase_mode_shots_made;
__local__ U8 			car_chase_modes_achieved;
U8			car_chase_mode_timer;
score_t 	car_chase_mode_score;
score_t 	car_chase_mode_temp_score;
score_t 	car_chase_mode_score_total_score;


//external variables

//internally called function prototypes  --external found at protos.h
void car_chase_reset (void);
void car_chase_player_reset (void);
void car_chase_effect_deff(void);
void car_chase_mode_init (void);
void car_chase_mode_expire (void);
void car_chase_mode_exit (void);


/****************************************************************************
 * mode definition structure
 ***************************************************************************/
struct timed_mode_ops car_chase_mode = {
	DEFAULT_MODE,
	.init = car_chase_mode_init,
	.exit = car_chase_mode_exit,
	.gid = GID_CAR_CHASE_MODE_RUNNING,
	.music = MUS_MD_CAR_CRASH,
	.deff_starting = DEFF_CAR_CHASE_START_EFFECT,
	.deff_running = DEFF_CAR_CHASE_EFFECT,
//	.deff_ending = DEFF_CAR_CHASE_END_EFFECT,
	.prio = PRI_GAME_MODE1,
	.init_timer = 33,
	.timer = &car_chase_mode_timer,
	.grace_timer = 2,
//	.pause = system_timer_pause,
};



/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void car_chase_reset (void) {
	flag_off (FLAG_IS_CARCHASE_MODE_ACTIVATED);
}//end of function



void car_chase_player_reset (void) {
	car_chase_reset();
	car_chase_modes_achieved = 0;
	car_chase_mode_shots_made = 0;
	score_zero(car_chase_mode_score_total_score);
}//end of function



void car_chase_mode_init (void) {
	car_chase_mode_shots_made = 0;
	flag_on (FLAG_IS_CARCHASE_MODE_ACTIVATED);
	++car_chase_modes_achieved;
	carchase_mode_on(); //at ramps.c
	sound_start (ST_SPEECH, SPCH_WUSS_SPARTAN, SL_4S, PRI_GAME_QUICK5);
	task_sleep_sec (2);
	sound_start (ST_SPEECH, SPCH_EXCUSE_ME, SL_4S, PRI_GAME_QUICK5);
	task_sleep_sec (1);
	sound_start (ST_SPEECH, SPCH_BETWEEN_YOU_N_ME, SL_4S, PRI_GAME_QUICK5);
	//flash lamp for a time
	score_zero(car_chase_mode_score);
	switch (car_chase_modes_achieved ){
		case 1: score_add(car_chase_mode_score, score_table[SC_15M]); break;
		case 2: score_add(car_chase_mode_score, score_table[SC_20M]); break;
		case 3: score_add(car_chase_mode_score, score_table[SC_25M]); break;
		default: score_add(car_chase_mode_score, score_table[SC_25M]);
	}//end of switch
	diverter_stop();//defined in divhold2.ct
}//end of function



void car_chase_mode_expire (void) {
	carchase_mode_off(); //at ramps.c
	flag_off (FLAG_IS_CARCHASE_MODE_ACTIVATED);
	if (flag_test(FLAG_IS_R_RAMP_CLAWREADY) ) 	rramp_clawready_on();
	else										rramp_clawready_off();
}//end of function

void car_chase_mode_exit (void) { car_chase_mode_expire();}


/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (car_chase, music_refresh)  	{ timed_mode_music_refresh (&car_chase_mode); }
CALLSET_ENTRY (car_chase, end_ball) 		{ if (timed_mode_running_p(&car_chase_mode) ) timed_mode_end (&car_chase_mode); }
CALLSET_ENTRY (car_chase, display_update) 	{ timed_mode_display_update (&car_chase_mode); }

CALLSET_ENTRY (car_chase, start_player) 	{ car_chase_player_reset(); }
CALLSET_ENTRY (car_chase, start_ball) 		{ car_chase_reset(); }




/****************************************************************************
 * body
 *
 ***************************************************************************/
//this is called from car_crash.c
void start_car_chase(void) {
	timed_mode_begin (&car_chase_mode);//start mode
}//end of function


void car_chase_ramp_made(void) {
	++car_chase_mode_shots_made;
	U8 car_chase_SoundCounter;
	car_chase_SoundCounter = random_scaled(car_chase_TotalNumOfSounds);//from kernal/random.c
	sound_start (ST_SPEECH, car_chase_SoundsArray[car_chase_SoundCounter], SL_4S, PRI_GAME_QUICK2);
	deff_start (DEFF_CAR_CHASE_HIT_EFFECT);//under /kernel/deff.c

	score_zero(car_chase_mode_temp_score);
	switch (car_chase_modes_achieved ){
		case 1:
			score (SC_5M);
			score_add(car_chase_mode_temp_score, score_table[SC_5M]);
			break;
		case 2: //2nd time we are in car_chase - score differently
			score (SC_10M);
			score_add(car_chase_mode_temp_score, score_table[SC_10M]);
			break;
		case 3: //3rd time we are in car_chase - score differently
			score (SC_15M);
			score_add(car_chase_mode_temp_score, score_table[SC_15M]);
			break;
		default: //all cases past 3rd time we are in car_chase
			score (SC_15M);
			score_add(car_chase_mode_temp_score, score_table[SC_15M]);
			break;
	}//end of switch
	score_add (car_chase_mode_score, car_chase_mode_temp_score);
	score_add (car_chase_mode_score_total_score, car_chase_mode_temp_score);
}//end of function


/****************************************************************************
 * DMD display and sound effects
 ****************************************************************************/
void car_chase_start_effect_deff(void) {
	dmd_alloc_pair_clean ();
	sound_start (ST_SAMPLE, CAR_SKID, SL_2S, PRI_GAME_QUICK5);
	dmd_sched_transition (&trans_scroll_left_fast);
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Cent, "CAR_CHASE");
	dmd_show_low ();
	task_sleep_sec (1);
	dmd_sched_transition (&trans_scroll_left_fast);
	dmd_alloc_low_clean ();
	sound_start (ST_SAMPLE, CAR_SKID, SL_2S, PRI_GAME_QUICK5);
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Cent, "SHOOT RAMPS");
	dmd_show_low ();
	task_sleep_sec (1);
	dmd_alloc_low_clean ();
	sound_start (ST_SAMPLE, CAR_SKID, SL_2S, PRI_GAME_QUICK5);
	dmd_sched_transition (&trans_scroll_left_fast);
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Cent, "CAR_CHASE");
	dmd_show_low ();
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff








U8 CCalternator;
void car_chase_hit_effect_deff(void) {
	U8 i;
	CCalternator++;
	dmd_alloc_pair_clean ();
	if (CCalternator%2 == 0) {
		bitmap_blit (car1A_high_bits, 120 , 10);
		dmd_flip_low_high ();
		bitmap_blit (car1A_low_bits, 120 , 10); //move from right to left
		dmd_flip_low_high ();
		dmd_show2 ();
		task_sleep (TIME_100MS);
		dmd_clean_page_low ();
		dmd_clean_page_high ();
				bitmap_blit (car1B_high_bits, 112, 10);
				dmd_flip_low_high ();
				bitmap_blit (car1B_low_bits, 112, 10); //move from right to left
				dmd_flip_low_high ();
				dmd_show2 ();
				task_sleep (TIME_100MS);
				dmd_clean_page_low ();
				dmd_clean_page_high ();
		bitmap_blit (car1C_high_bits, 104 , 10);
		dmd_flip_low_high ();
		bitmap_blit (car1C_low_bits, 104 , 10); //move from right to left
		dmd_flip_low_high ();
		dmd_show2 ();
		task_sleep (TIME_66MS);
		dmd_clean_page_low ();
		dmd_clean_page_high ();
				bitmap_blit (car1D_high_bits, 96, 10);
				dmd_flip_low_high ();
				bitmap_blit (car1D_low_bits, 96, 10); //move from right to left
				dmd_flip_low_high ();
				dmd_show2 ();
				task_sleep (TIME_66MS);
				dmd_clean_page_low ();
				dmd_clean_page_high ();
		bitmap_blit (car1E_high_bits, 88 , 10);
		dmd_flip_low_high ();
		bitmap_blit (car1E_low_bits, 88 , 10); //move from right to left
		dmd_flip_low_high ();
		dmd_show2 ();
		task_sleep (TIME_66MS);
		dmd_clean_page_low ();
		dmd_clean_page_high ();

			for (i = 0; i < 8; i++) {
					bitmap_blit (car1_high_bits, 80 - 10*i, 10);
					dmd_flip_low_high ();
					bitmap_blit (car1_low_bits, 80 - 10*i, 10); //move from right to left
					dmd_flip_low_high ();
					dmd_show2 ();
					task_sleep (TIME_66MS);
					dmd_clean_page_low ();
					dmd_clean_page_high ();
			}//end of loop

			bitmap_blit (car1V_high_bits, 0, 10);
			dmd_flip_low_high ();
			bitmap_blit (car1V_low_bits, 0, 10); //move from right to left
			dmd_flip_low_high ();
			dmd_show2 ();
			task_sleep (TIME_66MS);
			dmd_clean_page_low ();
			dmd_clean_page_high ();
/*					bitmap_blit (car1W_high_bits, 0, 10);
					dmd_flip_low_high ();
					bitmap_blit (car1W_low_bits, 0, 10); //move from right to left
					dmd_flip_low_high ();
					dmd_show2 ();
					task_sleep (TIME_100MS);
					dmd_clean_page_low ();
					dmd_clean_page_high ();
*/
			bitmap_blit (car1X_high_bits, 0, 10);
			dmd_flip_low_high ();
			bitmap_blit (car1X_low_bits, 0, 10); //move from right to left
			dmd_flip_low_high ();
			dmd_show2 ();
			task_sleep (TIME_66MS);
			dmd_clean_page_low ();
			dmd_clean_page_high ();
/*					bitmap_blit (car1Y_high_bits, 0, 10);
					dmd_flip_low_high ();
					bitmap_blit (car1Y_low_bits, 0, 10); //move from right to left
					dmd_flip_low_high ();
					dmd_show2 ();
					task_sleep (TIME_100MS);
					dmd_clean_page_low ();
					dmd_clean_page_high ();
*/
			bitmap_blit (car1Z_high_bits, 0, 10);
			dmd_flip_low_high ();
			bitmap_blit (car1Z_low_bits, 0, 10); //move from right to left
			dmd_flip_low_high ();
			dmd_show2 ();
			task_sleep (TIME_66MS);
			dmd_clean_page_low ();
			dmd_clean_page_high ();


	}
	/*************************************
	 * CAR 2
	 *************************************/
		else {
			bitmap_blit (car2B_high_bits, 120 , 10);
			dmd_flip_low_high ();
			bitmap_blit (car2B_low_bits, 120 , 10); //move from right to left
			dmd_flip_low_high ();
			dmd_show2 ();
			task_sleep (TIME_66MS);
			dmd_clean_page_low ();
			dmd_clean_page_high ();
					bitmap_blit (car2C_high_bits, 112 , 10);
					dmd_flip_low_high ();
					bitmap_blit (car2C_low_bits, 112, 10); //move from right to left
					dmd_flip_low_high ();
					dmd_show2 ();
					task_sleep (TIME_66MS);
					dmd_clean_page_low ();
					dmd_clean_page_high ();
			bitmap_blit (car2D_high_bits, 104 , 10);
			dmd_flip_low_high ();
			bitmap_blit (car2D_low_bits, 104, 10); //move from right to left
			dmd_flip_low_high ();
			dmd_show2 ();
			task_sleep (TIME_66MS);
			dmd_clean_page_low ();
			dmd_clean_page_high ();
					bitmap_blit (car2E_high_bits, 96, 10);
					dmd_flip_low_high ();
					bitmap_blit (car2E_low_bits, 96, 10); //move from right to left
					dmd_flip_low_high ();
					dmd_show2 ();
					task_sleep (TIME_66MS);
					dmd_clean_page_low ();
					dmd_clean_page_high ();

			for (i = 0; i < 6; i++) {
					bitmap_blit (car2_high_bits, 88 - 14*i, 10);
					dmd_flip_low_high ();
					bitmap_blit (car2_low_bits, 88 - 14*i, 10); //move from right to left
					dmd_flip_low_high ();
					dmd_show2 ();
					task_sleep (TIME_66MS);
					dmd_clean_page_low ();
					dmd_clean_page_high ();
			}//end of loop
		}//end of else
	deff_exit ();
}//end of mode_effect_deff




void car_chase_effect_deff(void) {
	U8 i = 0;
	for (;;) {
		if (++i % 5 == 0) 	{
			sound_start (ST_SAMPLE, CAR_SKID, SL_2S, PRI_GAME_QUICK5);
			dmd_sched_transition (&trans_scroll_left_fast);
		}
		dmd_alloc_low_clean ();
		font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Top, "CAR_CHASE");
		sprintf ("%d SEC LEFT,  %d HIT", car_chase_mode_timer, car_chase_mode_shots_made);
		font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_3, sprintf_buffer);
		sprintf_score (car_chase_mode_score);
		font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_4, sprintf_buffer);
		dmd_show_low ();
		task_sleep (TIME_500MS);
	}//END OF ENDLESS LOOP
}//end of mode_effect_deff





void car_chase_end_effect_deff(void) {
	dmd_alloc_low_clean ();
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Top, "CAR_CHASE");
	sprintf("COMPLETE");
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Bot, sprintf_buffer);
	dmd_show_low ();
	task_sleep_sec (2);
	deff_exit ();
	}//end of mode_effect_deff

