/*
 * demolition man
 * cryoprison.c
 * 
 * written by James Cardona
 *
 * cryoprison multiball
 *
 *
 * */
/* CALLSET_SECTION (cryoprison, __machine5__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct
#include "cryoprison.h"

//local variables
score_t		cryoprison_score;
U8			cryoprison_jackpot_shots_made;
U8			cryoprison_MessageCounter;
__boolean	cryoprison_start_music;
U8 cryoprison_display_counter;
U8 CRYO_TOGGLE;
U8 snake_pos;
__boolean	cryoprison_ballsave;

//external variables
extern U8			NumBallsFrozen; //from lock_freeze_mbstart.c

//internally called function prototypes  --external found at protos.h
void cryoprison_player_reset (void);



/****************************************************************************
 * multiball definition structure
 ***************************************************************************/
struct mb_mode_ops cryoprison_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB,
	.deff_starting = DEFF_CRYOPRISON_START_EFFECT,
	.deff_running = DEFF_CRYOPRISON_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms
};
//task_gid_t gid_running;
//task_gid_t gid_in_grace;


/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void cryoprison_player_reset (void) {
	flag_off(FLAG_IS_CRYOPRISON_MB_RUNNING);
	score_zero(cryoprison_score);
	cryoprison_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	cryoprison_start_music = FALSE;
}//end of function


CALLSET_ENTRY (cryoprison, start_player) { cryoprison_player_reset(); }



/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (cryoprison, music_refresh)  {
//	if (cryoprison_start_music)				music_request (SIREN, PRI_GAME_QUICK8);
//	else 									mb_mode_music_refresh (&cryoprison_mode);
	if (flag_test(FLAG_IS_CRYOPRISON_MB_RUNNING))	music_request (MUS_MB, PRI_GAME_QUICK7);
}//end of function




CALLSET_ENTRY (cryoprison, display_update) {
	if (flag_test(FLAG_IS_CRYOPRISON_MB_RUNNING))
			deff_start_bg (DEFF_CRYOPRISON_EFFECT, PRI_MULTIBALL);
}//end of function



CALLSET_ENTRY (cryoprison, end_ball) {
	if (flag_test(FLAG_IS_CRYOPRISON_MB_RUNNING)) {
		mb_mode_end_ball (&cryoprison_mode);
		jackpot_reset();
		end_super_jackpot_reminder();
		flag_off(FLAG_IS_CRYOPRISON_MB_RUNNING);

		if (!flag_test(FLAG_BACK_IN_THE_FRIDGE_ACTIVATED) )
			enable_back_in_the_fridge(); //at completion of our 4th MB we enable the wizard mode
	}
}//end of function



//puts in grace period if set
CALLSET_ENTRY (cryoprison, single_ball_play) {
	if (flag_test(FLAG_IS_CRYOPRISON_MB_RUNNING)) {
		mb_mode_end_ball (&cryoprison_mode);
		end_super_jackpot_reminder();
		combo_init();
		diverter_check();

		enable_back_in_the_fridge(); //at completion of our 4th MB we enable the wizard mode

		//this acts as kind of a grace period for the jackpots
		task_sleep_sec(3);
		flag_off(FLAG_IS_CRYOPRISON_MB_RUNNING);
		jackpot_reset();
	}
}//end of function



//if a ball drains during the mode and with time still on the ballsave timer - send it back in play
CALLSET_BOOL_ENTRY (cryoprison, ball_drain) { //thrown by device.c
	if	(flag_test(FLAG_IS_CRYOPRISON_MB_RUNNING)
		&& cryoprison_ballsave)	{
		sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK5);
		serve_ball_auto ();
		return FALSE; //this is not a valid drain, don't count it
	}
	else return TRUE; //this is a valid drain
}//end of callset








/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
void cryoprison_ballsave_task (void) {
	task_sleep_sec(15);
	cryoprison_ballsave = FALSE;
	task_exit();
}//end of function




void cryoprison_start_sounds (void) {
	U8 i;
	for(i = 0; i < 6; i++) {
		sound_start (ST_ANY, SIREN, SL_1S, PRI_GAME_QUICK5);
		task_sleep (TIME_500MS);
	}
	task_exit();
}//end of function





void cryoprison_start(U8 num) {
	kill_combos();
//	cryoprison_start_music = TRUE; //for to play the helicopter instead of the music
	task_create_gid1 (GID_CRYOPRISON_START_NOISE, cryoprison_start_sounds);
	flag_on(FLAG_IS_CRYOPRISON_MB_RUNNING);
	cryoprison_display_counter = 0;
	CRYO_TOGGLE = 0;
	snake_pos = 0;
	cryoprison_ballsave = TRUE;
	mb_mode_start(&cryoprison_mode);
	multiball_started();//reset all MB start criteria for next time

	score_add (cryoprison_score, score_table[CRYOPRISON_MB_SCORE]);
	score (CRYOPRISON_MB_SCORE);

	deff_start (DEFF_CRYOPRISON_START_EFFECT);
	diverter_stop();//defined in divhold2.ct
	task_kill_gid (GID_CR_LIGHTS);

	//LIGHTS
			lamp_tristate_flash(LM_CRYOPRISON_MULTIBALL);
			task_sleep (TIME_2S);
			lamp_tristate_on (LM_CRYOPRISON_MULTIBALL);
			lamp_tristate_off (LM_FREEZE_1);
			lamp_tristate_off (LM_FREEZE_2);
			lamp_tristate_off (LM_FREEZE_3);
			lamp_tristate_off (LM_FREEZE_4);

	//SOUNDS
			U8 	cryoprison_SoundCounter;
			cryoprison_SoundCounter = random_scaled(2);//from kernal/random.c - pick number from 0 to 2
			if (cryoprison_SoundCounter == 0)
				sound_start (ST_SPEECH, SPCH_SIMON_SAYS_SLY, SL_4S, PRI_GAME_QUICK5);
			else
				sound_start (ST_SPEECH, SPCH_PHOENIX_SHORT, SL_4S, PRI_GAME_QUICK5);
	task_sleep (TIME_3S);
	sound_start (ST_SPEECH, SPCH_SIMON_SAYS, SL_4S, PRI_GAME_QUICK5);
	cryoprison_start_music = FALSE; //for to kill the music

	//serve balls
	set_ball_count (5);
	task_create_gid1 (GID_CRYOPRISON_BALL_SAVE, cryoprison_ballsave_task);

	task_sleep (TIME_3S);
	set_all_jackpots(); //all 6 lit
}//end of function



//jackpot shot
void cryoprison_jackpot_made(void) {
	score_add (cryoprison_score, score_table[CRYOPRISON_JP_MB_SCORE]);
	score (CRYOPRISON_JP_MB_SCORE);
	deff_start (DEFF_CRYOPRISON_JACKPOT_EFFECT);
	choose_multiple_random_jackpot(3);

	if (IN_TEST) {	start_super_jackpot_reminder(); }
	else			if (cryoprison_jackpot_shots_made % 5 == 0) 	start_super_jackpot_reminder();
}//end of function



void cryoprison_award_super_jackpot(void) {
	score_add (cryoprison_score, score_table[CRYOPRISON_SUPER_JP_MB_SCORE]);
	score (CRYOPRISON_SUPER_JP_MB_SCORE);
	deff_start(DEFF_CRYOPRISON_SUPER_JACKPOT);
}//end of function





/****************************************************************************
 *
 * DMD display and sound effects
 *
 ****************************************************************************/
void cryoprison_super_jackpot_deff (void) {
	U8 i;

	for (i = 0; i < 8; i++) {
		switch (i) {
				case 0: sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK5); break;
				case 4: sound_start (ST_SPEECH, SPCH_HURRY_UP, SL_2S, PRI_GAME_QUICK5); break;
				case 8: sound_start (ST_SPEECH, SPCH_CLOSE_ENOUGH, SL_2S, PRI_GAME_QUICK5); break;
				case 1:
				case 3:
				case 5:
				case 7: sound_start (ST_ANY, EXPLOSION1_SHORT, SL_2S, PRI_GAME_QUICK5);
			}//END OF SWITCH
			dmd_sched_transition (&trans_scroll_up);
		dmd_alloc_low_clean ();
		font_render_string_center (&font_fireball, 64, 8, "SUPER");
		font_render_string_center (&font_fireball, 64, 24, "JACKPOT");
		dmd_show_low ();
	}//end of loop
	sample_start (MACHINE14_LONG, SL_1S);
	task_sleep (TIME_500MS);

	speech_start (SPCH_SUPER_JACKPOT, SL_1S);
	task_sleep_sec (1);
	deff_exit ();
}//end of function




void cryoprison_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void cryoprison_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void cryoprison_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_1, "CRYOPRISON");
	font_render_string_center (&font_steel, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);
}


void cryoprison_start_effect_deff(void) {
	U16 fno;
	dmd_alloc_pair_clean ();// Clean both pages
	cryoprison_animation_display_effect (IMG_CRYOPRISON_E1_START, IMG_CRYOPRISON_E1_END);

	cryoprison_frame_bitfade_fast(IMG_CRYOPRISON_E2_START);

	cryoprison_animation_display_effect (IMG_CRYOPRISON_E2_START, IMG_CRYOPRISON_E2_END);

	cryoprison_frame_bitfade_fast(IMG_CAPSIMON_C_START);

		dmd_alloc_pair_clean ();// Clean both pages
	for (fno = IMG_CAPSIMON_C_START; fno <= IMG_CAPSIMON_C_END; fno += 2) {
		dmd_map_overlay ();
		dmd_clean_page_low ();
		font_render_string_center (&font_steel, DMD_MIDDLE_X - 30, DMD_BIG_CY_Top, "CRYO");
		font_render_string_center (&font_steel, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "PRISON");
		dmd_text_outline ();
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_overlay_outline ();
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
	task_sleep_sec (2);
	deff_exit ();
}//end of mode_effect_deff



void cryoprison_jackpot_sounds_task(void) {
	U8 			cryoprison_MessageCounter;
	cryoprison_MessageCounter = random_scaled(3);
	if (++cryoprison_jackpot_shots_made % 2 == 0) {
			switch (cryoprison_MessageCounter) {
				case 0: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_WES, SL_2S, PRI_GAME_QUICK5); break;
				case 1: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_SLY, SL_2S, PRI_GAME_QUICK5); break;
				case 2: 	sound_start (ST_SPEECH, SPCH_DOUBLE, SL_2S, PRI_GAME_QUICK5); break;
			}//end of switch
	}//end of if
	else {
		switch (cryoprison_MessageCounter) {
			case 0: 	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK5); break;
			case 1: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK5); break;
			case 2: 	sound_start (ST_SPEECH, SPCH_UHHN, SL_2S, PRI_GAME_QUICK5); break;
		}//end of switch
	}//end of else
	task_sleep (TIME_500MS);
	sound_start (ST_EFFECT, FREEZE5, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, FREEZE5, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, FREEZE5, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, FREEZE5, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, EJECT, SL_2S, PRI_GAME_QUICK5);
	task_sleep (TIME_500MS);
	task_exit();
}//end of mode_effect_deff






U8 			cryoprison_jackpot_MessageCounter;
void cryoprison_jackpot_effect_deff(void) {
//	if (++cryoprison_jackpot_MessageCounter > 3) cryoprison_jackpot_MessageCounter = 0;
	 cryoprison_jackpot_MessageCounter = random_scaled(4);
	dmd_clean_page_high ();//
	dmd_clean_page_low ();//

	task_create_gid1 (GID_CRYOPRISON_JACKPOT_SOUND, cryoprison_jackpot_sounds_task);

	switch (cryoprison_jackpot_MessageCounter) {
		default:
		case 0:
			cryoprison_animation_display_effect (IMG_CAPSIMON_C_START, IMG_CAPSIMON_C_END);
			cryoprison_frame_with_words_display_steel_effect (IMG_CAPSIMON_C_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 1:
			cryoprison_animation_display_effect (IMG_CRYOPRISON_E2_START, IMG_CRYOPRISON_E2_END);
			cryoprison_frame_with_words_display_steel_effect (IMG_CRYOPRISON_E2_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 2:
			cryoprison_animation_display_effect (IMG_CRYOPRISON_E1_START, IMG_CRYOPRISON_E1_END);
			cryoprison_frame_with_words_display_steel_effect (IMG_CRYOPRISON_E1_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 3:
			cryoprison_animation_display_effect (IMG_DR_COCTEAU_B_START, IMG_DR_COCTEAU_B_END);
			cryoprison_frame_with_words_display_steel_effect (IMG_DR_COCTEAU_B_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		}//end of switch
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff






void show_snake (U8 section) {
	U8 j;
	U8 i;

	for (i = 0; i < section; i++) {
			for (j = 0; j < 4; j++) {
					switch (j) {
					case 0: 	bitmap_blit (cryoprison_snake1_bits, i*16, 1); 	 	bitmap_blit (cryoprison_snake4_bits, 124-(i*16), 27); 	break;
					case 1: 	bitmap_blit (cryoprison_snake2_bits, i*16 + 4, 1);  bitmap_blit (cryoprison_snake3_bits, 124-(i*16+4), 27); 	break;
					case 2: 	bitmap_blit (cryoprison_snake3_bits, i*16 + 8, 1); 	bitmap_blit (cryoprison_snake2_bits, 124-(i*16+8), 27); 	break;
					case 3: 	bitmap_blit (cryoprison_snake4_bits, i*16 + 12, 1); bitmap_blit (cryoprison_snake1_bits, 124-(i*16+12), 27); 	break;
					} //end of case
			} //end of j loop
	} //end of i loop


	for (j = 0; j < 4; j++) {
		switch (j) {
			case 0: 	bitmap_blit (cryoprison_snake1_bits, section * 16, 1); 	 	bitmap_blit (cryoprison_snake4_bits, 124-(section*16), 27); 	break;
			case 1: 	bitmap_blit (cryoprison_snake2_bits, section * 16 + 4, 1);  bitmap_blit (cryoprison_snake3_bits, 124-(section*16+4), 27); break;
			case 2: 	bitmap_blit (cryoprison_snake3_bits, section * 16 + 8, 1);  bitmap_blit (cryoprison_snake2_bits, 124-(section*16+8), 27); break;
			case 3: 	bitmap_blit (cryoprison_snake4_bits, section * 16 + 12, 1); bitmap_blit (cryoprison_snake1_bits, 124-(section*16+12), 27); break;
		}//end of case

		dmd_show_low ();//shows a 4 color image
		task_sleep (TIME_200MS);
	}//end of j loop

	dmd_alloc_pair_clean();
}//end of func



void cryoprison_effect_deff (void) {
	dmd_alloc_pair_clean();

	for (;;) {
		dmd_draw_thin_border (dmd_low_buffer);

		font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Top - 2, "CRYOPRISON");

		sprintf_score(current_score);
		font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_3 - 2, sprintf_buffer);

		if (CRYO_TOGGLE == 0) 		{ sprintf ("15 MILLION"); font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Bot - 2, sprintf_buffer); }
		else if (CRYO_TOGGLE == 1)	{ sprintf ("JACKPOT LIT"); font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Bot - 2, sprintf_buffer); }
		else if (CRYO_TOGGLE == 2)	{sprintf ("%d JACKPOTS", cryoprison_jackpot_shots_made); font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Bot - 2, sprintf_buffer); }
		else if (CRYO_TOGGLE == 3)	{ if (flag_test(FLAG_IS_SUPER_JACKPOT_ACTIVATED) )	sprintf ("SUPER LIT");
									else 											sprintf ("%d FOR SUPER", 5 - (cryoprison_jackpot_shots_made % 5) );
									font_render_string_center (&font_steel, DMD_MIDDLE_X,  DMD_BIG_CY_Bot - 2, sprintf_buffer); }

		show_snake(snake_pos);  // takes approx 1.5 seconds

		if (snake_pos < 7) snake_pos ++;
		else snake_pos = 0;

		if (++cryoprison_display_counter % 7 == 0) { if (++CRYO_TOGGLE > 3) CRYO_TOGGLE = 0; } //change CRYO_TOGGLE once per second
	}//END OF ENDLESS LOOP
}//end of function

