/*
 * demolition man
 * demotime.c
 * 
 * written by James Cardona
 *
 * demotime multiball
 *
 *
 * */
/* CALLSET_SECTION (demotime, __machine2__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct
#include "search.h"
//constants
const U8	DEMOTIME_EASY_GOAL = 5;
const U8	DEMOTIME_HARD_GOAL = 8;
const U8	DEMOTIME_GOAL_INCREMENT = 3;

//local variables
__boolean	demotime_start_music;
score_t		demotime_score;
U8			demotime_jackpot_shots_made;
U8			demotime_MessageCounter;
__local__ U8			demotime_counter;
__local__ U8			demotime_goal;
__boolean	demotime_ballsave;


//internally called function prototypes  --external found at protos.h
void demotime_player_reset (void);



/****************************************************************************
 * multiball definition structure
 ***************************************************************************/
struct mb_mode_ops demotime_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB_B,
//	.deff_starting = DEFF_DEMOTIME_START_EFFECT,
	.deff_running = DEFF_DEMOTIME_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms
};
//task_gid_t gid_running;
//task_gid_t gid_in_grace;



/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void demotime_player_reset (void) {
	demotime_counter = 0;
	demotime_goal = DEMOTIME_EASY_GOAL;
	flag_off(FLAG_IS_DEMOTIME_ENABLED);
	flag_off(FLAG_IS_DEMOTIME_RUNNING);
	flag_off(FLAG_IS_DEMOTIME_IS_STARTING);
	score_zero(demotime_score);
	demotime_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	demotime_start_music = FALSE;
	lamp_tristate_off (LM_DEMO_TIME);

#ifdef CONFIG_DIFFICULTY_LEVEL
		if (system_config.difficulty == EASY) 	demotime_goal = DEMOTIME_EASY_GOAL;
		else									demotime_goal = DEMOTIME_HARD_GOAL;
#endif
}//end of function



CALLSET_ENTRY (demotime, start_player) { demotime_player_reset(); }



/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (demotime, music_refresh)  {
	if (demotime_start_music)				music_request (LOW_HORN, PRI_GAME_QUICK8);
	else if	(flag_test(FLAG_IS_DEMOTIME_RUNNING))	music_request (MUS_MB_B, PRI_GAME_QUICK7);
}//end of function



CALLSET_ENTRY (demotime, display_update) {
	if (flag_test(FLAG_IS_DEMOTIME_RUNNING))
		deff_start_bg (DEFF_DEMOTIME_EFFECT, PRI_MULTIBALL);
}//end of function



CALLSET_ENTRY (demotime, end_ball) {
	if (flag_test(FLAG_IS_DEMOTIME_RUNNING)) {
		mb_mode_end_ball (&demotime_mode);
		jackpot_reset();
		end_super_jackpot_reminder();
		lamp_tristate_off (LM_DEMO_TIME);
		flag_off(FLAG_IS_DEMOTIME_RUNNING);
		flag_off(FLAG_IS_DEMOTIME_ENABLED);
	}
}//end of function



//puts in grace period if set, otherwise ends mode
CALLSET_ENTRY (demotime, single_ball_play) {
	if (flag_test(FLAG_IS_DEMOTIME_RUNNING)) {
		mb_mode_end_ball (&demotime_mode);
		end_super_jackpot_reminder();
		lamp_tristate_off (LM_DEMO_TIME);
		flag_off(FLAG_IS_DEMOTIME_ENABLED);
		combo_init();
		diverter_check();

		//this acts as kind of a grace period for the jackpots
		task_sleep_sec(3);
		flag_off(FLAG_IS_DEMOTIME_RUNNING);
		jackpot_reset();
	}//end of if
}//end of function




//if a ball drains during the mode and with time still on the ballsave timer - send it back in play
CALLSET_BOOL_ENTRY (demotime, ball_drain) { //thrown by device.c
	if	(flag_test(FLAG_IS_DEMOTIME_RUNNING)
		&& demotime_ballsave)	{
		sound_start (ST_SPEECH, EXPLOSION, SL_2S, PRI_GAME_QUICK5);
		serve_ball_auto ();
		return FALSE; //this is not a valid drain, don't count it
	}
	else return TRUE; //this is a valid drain
}//end of callset







/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
void demotime_ballsave_task (void) {
	task_sleep_sec(15);
	demotime_ballsave = FALSE;
	task_exit();
}//end of function


//MAKING ANY OF THE CLAW MODE SHOTS CALLS THIS
void demotime_increment (void) {
	if (++demotime_counter >= demotime_goal) {
		flag_on(FLAG_IS_DEMOTIME_ENABLED);
		deff_start (DEFF_DEMOTIME_INFO_EFFECT);//under /kernel/deff.c
		lamp_tristate_flash (LM_DEMO_TIME);
	}
}//end of function


//for testing
void demotime_increment_all (void) {
		flag_on(FLAG_IS_DEMOTIME_ENABLED);
		deff_start (DEFF_DEMOTIME_INFO_EFFECT);//under /kernel/deff.c
		lamp_tristate_flash (LM_DEMO_TIME);
}//end of function



//ONCE ENABLED IT IS STARTED BY A UNDERGROUND SHOT
void demotime_start(void) {
	ball_search_monitor_stop ();
	kill_combos();
	demotime_ballsave = TRUE;
	demotime_start_music = TRUE;
	flag_on(FLAG_IS_DEMOTIME_IS_STARTING);
	flag_on(FLAG_IS_DEMOTIME_RUNNING);
	flag_off(FLAG_IS_DEMOTIME_ENABLED);
	mb_mode_start(&demotime_mode);
	diverter_stop();//defined in divhold2.ct
	task_kill_gid (GID_CR_LIGHTS);

	//LIGHTS
	lamp_tristate_on (LM_DEMO_TIME);

	//reset all start criteria for next time
	demotime_goal += (DEMOTIME_GOAL_INCREMENT);
	demotime_counter = 0;

	deff_start_sync(DEFF_DEMOTIME_START_EFFECT);

	set_all_jackpots();
	set_ball_count (5);

	task_create_gid1 (GID_DEMOTIME_BALL_SAVE, demotime_ballsave_task);
	sol_request_async(SOL_BOTTOM_POPPER);
	flag_off(FLAG_IS_DEMOTIME_IS_STARTING);
	ball_search_monitor_start ();
}//end of function



//jackpot shot
void demotime_jackpot_made(void) {
	score_add (demotime_score, score_table[DEMOTIME_JP_MB_SCORE]);
	score (DEMOTIME_JP_MB_SCORE);
	deff_start (DEFF_DEMOTIME_JACKPOT_EFFECT);
}//end of function



/****************************************************************************
 *
 * DMD display and sound effects
 *
 ****************************************************************************/
void demotime_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void demotime_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void demotime_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_steel, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);
}



void demotime_info_effect_deff(void) {
	dmd_clean_page_high ();
	dmd_clean_page_low ();
	font_render_string_center (&font_term6, DMD_MIDDLE_X, DMD_MED_CY_1, "SHOOT SUBWAY");
	font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_MED_CY_2, "FOR");

	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "DEMOLITION TIME");
	dmd_show_low();
	task_sleep_sec (3);
	deff_exit ();
}//end of mode_effect_deff




void demotime_start_effect_deff(void) {
	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);
	sound_start (ST_SPEECH, SPCH_YOU_AND_ME, SL_4S, PRI_GAME_QUICK5);
	demotime_animation_display_effect (IMG_FORTRESS_D1_START, IMG_FORTRESS_D1_END);

	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_steel, DMD_MIDDLE_X - 20, DMD_BIG_CY_Top, "DEMOLITION");
	font_render_string_center (&font_steel, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "TIME");
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(IMG_FORTRESS_D1_END);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);

	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);
	demotime_frame_bitfade_fast(IMG_FIGHT_A_START);
	sound_start (ST_SPEECH, SPCH_MUST_HAVE_HURT, SL_4S, PRI_GAME_QUICK5);
	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);
	demotime_animation_display_effect (IMG_FIGHT_A_START, IMG_FIGHT_A_END);

	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_steel, DMD_MIDDLE_X - 20, DMD_BIG_CY_Top, "DEMOLITION");
	font_render_string_center (&font_steel, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "TIME");
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(IMG_MUSEUM_D2_END);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);

	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);
	demotime_frame_bitfade_fast(IMG_WASTELAND_A1_START);
	sound_start (ST_SPEECH, SPCH_IN_THIS_CENTURY, SL_4S, PRI_GAME_QUICK5);
	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);
	demotime_animation_display_effect (IMG_WASTELAND_A1_START, IMG_WASTELAND_A1_END);

		dmd_map_overlay ();
		dmd_clean_page_low ();
		font_render_string_center (&font_steel, DMD_MIDDLE_X + 10, DMD_BIG_CY_Top, "DEMOLITION");
		font_render_string_center (&font_steel, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "TIME");
		dmd_text_outline ();
		dmd_alloc_pair ();
		frame_draw(IMG_WASTELAND_A1_END);
		dmd_overlay_outline ();
		dmd_show2 ();
		task_sleep (TIME_100MS);

	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);
	demotime_frame_bitfade_fast(IMG_CAPSIMON_C_START);
	sound_start (ST_SPEECH, SPCH_JOHN_SPARTAN, SL_4S, PRI_GAME_QUICK5);
	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);
	demotime_animation_display_effect (IMG_CAPSIMON_C_START, IMG_CAPSIMON_C_END);

		dmd_map_overlay ();
		dmd_clean_page_low ();
		font_render_string_center (&font_steel, DMD_MIDDLE_X + 10, DMD_BIG_CY_Top, "DEMOLITION");
		font_render_string_center (&font_steel, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "TIME");
		dmd_text_outline ();
		dmd_alloc_pair ();
		frame_draw(IMG_CAPSIMON_C_END);
		dmd_overlay_outline ();
		dmd_show2 ();
		task_sleep (TIME_100MS);

	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);
	sound_start (ST_SPEECH, SPCH_DEMOLITION_MAN, SL_4S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	demotime_start_music = FALSE; //kill the start music
	deff_exit ();
}//end of mode_effect_deff



U8 			demotime_SoundCounter;
void demotime_jackpot_sounds_task(void) {
	if (IN_TEST) {	if (++demotime_SoundCounter > 5) demotime_SoundCounter = 0; }
	else			demotime_SoundCounter = random_scaled(6);

	switch (demotime_SoundCounter) {
		case 0: 	sound_start (ST_SPEECH, SPCH_TRESPASSING, SL_2S, PRI_GAME_QUICK5); break;
		case 1: 	sound_start (ST_SPEECH, SPCH_ARREST, SL_2S, PRI_GAME_QUICK5); break;
		case 2: 	sound_start (ST_SPEECH, SPCH_DREAMIN_KILLING_YOU, SL_2S, PRI_GAME_QUICK5); break;
	}//end of switch
	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, GUNSHOT, SL_2S, PRI_GAME_QUICK5);
	task_sleep (TIME_500MS);
	switch (demotime_SoundCounter) {
		case 3: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK5); break;
		case 4: 	sound_start (ST_SPEECH, SPCH_DONT_WORRY, SL_2S, PRI_GAME_QUICK5); break;
		case 5: 	sound_start (ST_SPEECH, SPCH_KEEP_DREAMING, SL_2S, PRI_GAME_QUICK5); break;
	}//end of switch
	task_exit();
}//end of mode_effect_deff



U8 			demotime_MessageCounter;
void demotime_jackpot_effect_deff(void) {
	dmd_clean_page_high ();//
	dmd_clean_page_low ();//

	if (IN_TEST) {	if (++demotime_MessageCounter > 3) demotime_MessageCounter = 0; }
	else			demotime_MessageCounter = random_scaled(4);

	task_create_gid1 (GID_DEMOTIME_JACKPOT_SOUND, demotime_jackpot_sounds_task);

	switch (demotime_MessageCounter) {
	//FROM FORTRESS
		default:
		case 0:
			demotime_animation_display_effect (IMG_FORTRESS_D1_START, IMG_FORTRESS_D1_END);
			demotime_frame_with_words_display_steel_effect (IMG_FORTRESS_D1_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "DEMOLITION");
			break;

	//FROM MUSEUM
		case 1:
			demotime_animation_display_effect (IMG_FIGHT_A_START, IMG_FIGHT_A_END);
			demotime_frame_with_words_display_steel_effect (IMG_FIGHT_A_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "DEMOLITION");
			break;

	//FROM CRYOPRISON
		case 2:
			demotime_animation_display_effect (IMG_CAPSIMON_C_START, IMG_CAPSIMON_C_END);
			demotime_frame_with_words_display_steel_effect (IMG_CAPSIMON_C_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "DEMOLITION");
			break;

	//FROM WASTELAND
		case 3:
			demotime_animation_display_effect (IMG_WASTELAND_A1_START, IMG_WASTELAND_A1_END);
			demotime_frame_with_words_display_steel_effect (IMG_WASTELAND_A1_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "DEMOLITION");
			break;
		}//end of switch
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff




void demotime_effect_deff (void) {
	U8 demotime_display_counter = 0;
	__boolean TOGGLE = FALSE;
	dmd_alloc_pair_clean();

	for (;;) {
			dmd_clean_page_low ();
			dmd_draw_thin_border (dmd_low_buffer);
			font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Top - 2, "DEMOTIME");

			sprintf_score(current_score);
			font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_3, sprintf_buffer);

			if (demotime_display_counter % 10 != 0) { //draw for 9/10 and blank for 1/10
						if (TOGGLE) 	sprintf ("15 MILLION");
						else 			sprintf ("JACKPOT LIT"); }
			else 						sprintf ("");
			font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Bot, sprintf_buffer);

			dmd_show_low ();
			task_sleep (TIME_200MS);

			demotime_display_counter++;
			if (demotime_display_counter >= 30) demotime_display_counter  = 0;
			if (demotime_display_counter % 10 == 0) { if (TOGGLE) TOGGLE = FALSE; else TOGGLE = TRUE; }//change TOGGLE once per second
	}//END OF ENDLESS LOOP
}//end of function

