/*
 * demolition man
 * fortress.c
 * 
 * written by James Cardona
 *
 * handles the lock freezes and the trigger of multiballs
 *
 *
 * */
/* CALLSET_SECTION (fortress, __machine3__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct

//local variables
score_t		fortress_score;
U8			fortress_jackpot_shots_made;
U8			fortress_MessageCounter;
__boolean	fortress_start_music;

//external variables
extern U8			NumBallsFrozen; //from lock_freeze_mbstart.c

//internally called function prototypes  --external found at protos.h
void fortress_player_reset (void);
void fortress_start_effect_deff(void);
void fortress_jackpot_effect1_deff(void);
void fortress_jackpot_effect2_deff(void);
void fortress_jackpot_effect3_deff(void);
void fortress_jackpot_effect(void);
void fortress_effect_deff (void);

/****************************************************************************
 * multiball definition structure
 ***************************************************************************/


struct mb_mode_ops fortress_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB, //handled below
	.deff_starting = DEFF_FORTRESS_START_EFFECT,
	.deff_running = DEFF_FORTRESS_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms

	//	.gid_running = GID_FORTRESS_MB,
	//.gid_in_grace = , //of type task_gid_t
};


/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void fortress_player_reset (void) {
	flag_off(FLAG_IS_FORTRESS_MB_RUNNING);
	score_zero(fortress_score);
	fortress_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	fortress_start_music = FALSE;
}//end of function



CALLSET_ENTRY (fortress, start_player) { fortress_player_reset(); }

/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (fortress, music_refresh)  {
	if (fortress_start_music)						music_request (HELICOPTER, PRI_GAME_QUICK8);
	else if (flag_test(FLAG_IS_FORTRESS_MB_RUNNING))	music_request (MUS_MB, PRI_GAME_QUICK7);
}//end of function

CALLSET_ENTRY (fortress, display_update) { mb_mode_display_update (&fortress_mode); }

CALLSET_ENTRY (fortress, end_ball) {
	if (flag_test(FLAG_IS_FORTRESS_MB_RUNNING)) {
		mb_mode_end_ball (&fortress_mode);
		jackpot_reset();
		flag_off(FLAG_IS_FORTRESS_MB_RUNNING);
		if (flag_test(FLAG_IS_R_RAMP_CLAWREADY) ) 	rramp_clawready_on();
		else										rramp_clawready_off();
	}
}//end of function

//puts in grace period if set
CALLSET_ENTRY (fortress, single_ball_play) {
	if (flag_test(FLAG_IS_FORTRESS_MB_RUNNING)) {
		mb_mode_end_ball (&fortress_mode);
		jackpot_reset();
		flag_off(FLAG_IS_FORTRESS_MB_RUNNING);
		if (flag_test(FLAG_IS_R_RAMP_CLAWREADY) ) 	rramp_clawready_on();
		else										rramp_clawready_off();
	}
}//end of function

/****************************************************************************
 * body
 *
 ***************************************************************************/
void fortress_start(void) {
	fortress_start_music = TRUE; //for to play the helicopter instead of the music
	flag_on(FLAG_IS_FORTRESS_MB_RUNNING);
	mb_mode_start(&fortress_mode);
	deff_start (DEFF_FORTRESS_START_EFFECT);
	multiball_started();//reset all MB start criteria for next time
	diverter_stop();//defined in divhold2.ct
	//LIGHTS
			lamp_tristate_flash(LM_FORTRESS_MULTIBALL);
			task_sleep (TIME_2S);
			lamp_tristate_on (LM_FORTRESS_MULTIBALL);
			lamp_tristate_off (LM_FREEZE_1);
			lamp_tristate_off (LM_FREEZE_2);
			lamp_tristate_off (LM_FREEZE_3);
			lamp_tristate_off (LM_FREEZE_4);

	//SOUNDS
			U8 	fortress_SoundCounter;
			fortress_SoundCounter = random_scaled(2);//from kernal/random.c - pick number from 0 to 2
			if (fortress_SoundCounter == 0)
				sound_start (ST_SPEECH, SPCH_SOMETHING_RIGHT_PREV_LIFE, SL_4S, PRI_GAME_QUICK5);
			else
				sound_start (ST_SPEECH, SPCH_SEND_MANIAC, SL_4S, PRI_GAME_QUICK5);
	task_sleep (TIME_3S);
	fortress_start_music = FALSE; //for to kill the music

	choose_random_jackpot();//randomize which jackpot shot to make
	//----------
	//serve balls
	//----------
			serve_ball_auto(); //add one ball to the playfield - NOT technically a multiball since doesn't change global ball count
}//end of function



//jackpot shot
void fortress_jackpot_made(void) {
	score_add (fortress_score, score_table[FORTRESS_MB_SCORE]);
	score (FORTRESS_MB_SCORE);
	fortress_jackpot_effect();
}//end of function



/****************************************************************************
 * DMD display and sound effects
 ****************************************************************************/
void fortress_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void fortress_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}



void fortress_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_steel, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




//30 frames - should last about 3 seconds
void fortress_start_effect_deff(void) {
	U8 			fortress_MessageCounter;
	U16 fno;

	fortress_MessageCounter = random_scaled(2);
	dmd_alloc_pair_clean();

	switch (fortress_MessageCounter) {
		default:
		case 0:
			fortress_animation_display_effect (IMG_FORTRESS_D1_START, IMG_FORTRESS_D1_END);
			fortress_frame_bitfade_fast(IMG_FORTRESS_D2_START);
			fortress_animation_display_effect (IMG_FORTRESS_D2_START, IMG_FORTRESS_D2_END);
			fortress_frame_bitfade_fast(IMG_FORTRESS_D3_START);
			fortress_animation_display_effect (IMG_FORTRESS_D3_START, IMG_FORTRESS_D3_END);
			fortress_frame_bitfade_fast(IMG_FORTRESS_D4_START);

			dmd_alloc_pair_clean ();// Clean both pages
			for (fno = IMG_FORTRESS_D4_START; fno <= IMG_FORTRESS_D4_END; fno += 2) {
				dmd_map_overlay ();
				dmd_clean_page_low ();
				font_render_string_center (&font_steel, DMD_MIDDLE_X - 20, DMD_BIG_CY_Top, "FORTRESS");
				font_render_string_center (&font_steel, DMD_MIDDLE_X - 15, DMD_BIG_CY_Bot, "MULTIBALL");
				dmd_text_outline ();
				dmd_alloc_pair ();
				frame_draw(fno);
				dmd_overlay_outline ();
				dmd_show2 ();
				task_sleep (TIME_100MS);
			}//end of inner loop
			break;
		case 1:
			fortress_animation_display_effect (IMG_FORTRESS_A_START, IMG_FORTRESS_A_END);
			fortress_frame_bitfade_fast(IMG_FORTRESS_B_START);
			fortress_animation_display_effect (IMG_FORTRESS_B_START, IMG_FORTRESS_B_END);
			dmd_map_overlay ();
			dmd_clean_page_low ();
			font_render_string_center (&font_steel, DMD_MIDDLE_X - 20, DMD_BIG_CY_Top, "FORTRESS");
			font_render_string_center (&font_steel, DMD_MIDDLE_X - 15, DMD_BIG_CY_Bot, "MULTIBALL");
			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(IMG_FORTRESS_B_END);
			dmd_overlay_outline ();
			dmd_show2 ();
			break;
	}//end of switch
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff



void fortress_jackpot_sounds_task(void) {
	U8 			fortress_MessageCounter;
	fortress_MessageCounter = random_scaled(3);
	if (++fortress_jackpot_shots_made % 2 == 0) {
			switch (fortress_MessageCounter) {
				case 0: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_WES, SL_2S, PRI_GAME_QUICK5); break;
				case 1: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_SLY, SL_2S, PRI_GAME_QUICK5); break;
				case 2: 	sound_start (ST_SPEECH, SPCH_DOUBLE, SL_2S, PRI_GAME_QUICK5); break;
			}//end of switch
	}//end of if
	else {
		switch (fortress_MessageCounter) {
			case 0: 	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK5); break;
			case 1: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK5); break;
			case 2: 	sound_start (ST_SPEECH, SPCH_UHHN, SL_2S, PRI_GAME_QUICK5); break;
		}//end of switch
	}//end of else
	task_sleep (TIME_500MS);
	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, RICOCHET, SL_2S, PRI_GAME_QUICK5);
	task_sleep (TIME_500MS);
	task_exit();
}//end of mode_effect_deff



void fortress_jackpot_effect(void) {
	deff_start (DEFF_FORTRESS_JACKPOT_EFFECT);
}//end of FUNCTION


U8 			fortress_MessageCounter;
void fortress_jackpot_effect_deff(void) {
//	if (++fortress_MessageCounter > 5) fortress_MessageCounter = 0; //for testing
	fortress_MessageCounter = random_scaled(5);
	dmd_alloc_pair_clean();

	task_create_gid1 (GID_FORTRESS_JACKPOT_SOUND, fortress_jackpot_sounds_task);

	switch (fortress_MessageCounter) {
		default:
		case 0:
			fortress_animation_display_effect (IMG_FORTRESS_A_START, IMG_FORTRESS_A_END);
			fortress_frame_with_words_display_steel_effect (IMG_FORTRESS_A_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Top, "JACKPOT");
			break;
		case 1:
			fortress_animation_display_effect (IMG_FORTRESS_B_START, IMG_FORTRESS_B_END);
			fortress_frame_with_words_display_steel_effect (IMG_FORTRESS_B_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 2:
			fortress_animation_display_effect (IMG_FORTRESS_D1_START, IMG_FORTRESS_D1_END);
			fortress_animation_display_effect (IMG_FORTRESS_D2_START, IMG_FORTRESS_D2_END);
			fortress_frame_with_words_display_steel_effect (IMG_FORTRESS_D2_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 3:
			fortress_animation_display_effect (IMG_FORTRESS_D3_START, IMG_FORTRESS_D3_END);
			fortress_animation_display_effect (IMG_FORTRESS_D4_START, IMG_FORTRESS_D4_END);
			fortress_frame_with_words_display_steel_effect (IMG_FORTRESS_D4_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 4:
			fortress_animation_display_effect (IMG_BURN_FORTRESS_START, IMG_BURN_FORTRESS_END);
			fortress_frame_with_words_display_steel_effect (IMG_BURN_FORTRESS_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Top, "JACKPOT");
			break;
		}//end of switch
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff




//the image is 4 color in 2 panes, so we must increment by 2's not 1's
U8 fortress_effect_deff_table[] = {	0, 2, 0, 2, 4, 2, 4, 2, 0, 0,
									2, 4, 6, 8, 6, 8, 4, 2, 0, 6,
									2, 6, 8, 4, 6, 8, 2, 0, 2, 0, 4, 2 };

void fortress_effect_deff (void) {
	U8 fortress_display_counter = 0;
	__boolean TOGGLE = FALSE;

	dmd_alloc_pair_clean();

	for (;;) {
			dmd_map_overlay ();
			dmd_clean_page_low ();
			dmd_draw_thin_border (dmd_low_buffer);
			font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Top, "FORTRESS");
			if (fortress_display_counter % 10 != 0) { //draw for 9/10 and blank for 1/10
						if (TOGGLE) 	sprintf ("15 MILLION");
						else 			sprintf ("JACKPOT LIT"); }
			else 						sprintf ("");

			font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Bot, sprintf_buffer);

			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(IMG_FORTRESS_RUN_0 + fortress_effect_deff_table[fortress_display_counter]);
			dmd_overlay_outline ();
			dmd_show2 ();
		task_sleep (TIME_200MS);

		fortress_display_counter++;
		if (fortress_display_counter >= 30) fortress_display_counter  = 0;
		if (fortress_display_counter % 10 == 0) { if (TOGGLE) TOGGLE = FALSE; else TOGGLE = TRUE; }//change TOGGLE once per second
	}//END OF ENDLESS LOOP
}//end of function

