/*
 * demolition man
 * huxley.c
 *
 * written by James Cardona
 *
 * Description:
 * wizrd mode started by completing at least 4 non-claw modes
 *
 * Scoring Description: (my rules)
 * scores 1 million per shot - everything scores
 *
 */
/* CALLSET_SECTION (huxley, __machine4__) */

#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct

//constants
const U8	HUXLEY_EASY_GOAL = 4;

//constants
const U8 	huxley_TotalNumOfSounds = 8; //num between 0 and N-1 == N total
const sound_code_t huxley_SoundsArray[] = { SPCH_WEEAHOO, 				SPCH_I_GOT_IT,							SPCH_WOAH,
											SPCH_WHAT_ARE_YOU_DOING, 	SPCH_DONT_YOU_WANT_SOMETHING_HAPPEN,	SPCH_COMPETITION,
											SPCH_EXCUSE_ME,				SPCH_SOME_ACTION};


//local variables

U8 						huxley_counter;
U8 						huxley_mode_shots_made;
U8						huxley_mode_timer;
U8						huxley_goal;
__local__ U8 			huxley_modes_achieved;
score_t 	huxley_mode_score;
score_t 	huxley_mode_last_score;
score_t 	huxley_mode_next_score;
score_t 	huxley_mode_score_total_score;
//external variables

//internally called function prototypes  --external found at protos.h
void huxley_reset (void);
void huxley_player_reset (void);
void huxley_mode_init (void);
void huxley_mode_expire (void);
void huxley_mode_exit (void);
void play_huxley_sounds(void);

/****************************************************************************
 * mode definition structure
 ***************************************************************************/
struct timed_mode_ops huxley_mode = {
	DEFAULT_MODE,
	.init = huxley_mode_init,
	.exit = huxley_mode_exit,
	.gid = GID_HUXLEY_MODE_RUNNING,
	.music = MUS_MB_B,//MUS_MB_A,
	.deff_starting = DEFF_HUXLEY_START_EFFECT,
	.deff_running = DEFF_HUXLEY_EFFECT,
//	.deff_ending = DEFF_HUXLEY_END_EFFECT,
	.prio = PRI_GAME_MODE3,
	.init_timer = 93,
	.timer = &huxley_mode_timer,
	.grace_timer = 2, //default is 2
//	.pause = system_timer_pause,
};



/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void huxley_reset (void) {
	flag_off (FLAG_IS_HUXLEY_RUNNING);
}//end of function



void huxley_player_reset (void) {
	huxley_goal = HUXLEY_EASY_GOAL;
	flag_off(FLAG_IS_HUXLEY_ENABLED);
	flag_off(FLAG_IS_HUXLEY_RUNNING);
	huxley_reset();
	huxley_counter = 0;
	huxley_modes_achieved = 0;
	huxley_mode_shots_made = 0;
	score_zero(huxley_mode_score_total_score);
}//end of function



void huxley_mode_init (void) {
	huxley_mode_shots_made = 0;
	flag_on (FLAG_IS_HUXLEY_RUNNING);
	++huxley_modes_achieved;
	diverter_stop();//defined in divhold2.ct

	score_zero(huxley_mode_score);
	score_zero(huxley_mode_last_score);
	score_zero(huxley_mode_next_score);

	score(HUXLEY_START_SCORE);
	score_add(huxley_mode_score, score_table[HUXLEY_START_SCORE]);
	score_add(huxley_mode_next_score, score_table[HUXLEY_MODE_HIT_SCORE]);
}//end of function



void huxley_mode_expire (void) {
	flag_off (FLAG_IS_HUXLEY_RUNNING);
	if (flag_test(FLAG_IS_R_RAMP_CLAWREADY) ) 	rramp_clawready_on();
	else										rramp_clawready_off();
}//end of function


void huxley_mode_exit (void) { huxley_mode_expire();}


/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (huxley, music_refresh)  	{ timed_mode_music_refresh (&huxley_mode); }
CALLSET_ENTRY (huxley, end_ball) 		{ if (timed_mode_running_p(&huxley_mode) ) timed_mode_end (&huxley_mode); }
CALLSET_ENTRY (huxley, display_update) 	{ timed_mode_display_update (&huxley_mode); }

CALLSET_ENTRY (huxley, start_player) 	{ huxley_player_reset(); }
CALLSET_ENTRY (huxley, start_ball) 		{ huxley_reset(); }




/****************************************************************************
 * body
 *
 ***************************************************************************/
void huxley_increment (void) {
	if (++huxley_counter >= huxley_goal) {
		flag_on(FLAG_IS_HUXLEY_ENABLED);
		deff_start (DEFF_HUXLEY_INFO_EFFECT);//under /kernel/deff.c
	}
}//end of function



//Once huxley mode is enabled it is started by a huxley shot (backwards to retina scan)
void huxley_begin(void) {
	timed_mode_begin (&huxley_mode);//start mode
	huxley_goal += (HUXLEY_EASY_GOAL * 2);
	flag_off(FLAG_IS_HUXLEY_ENABLED);
	flag_on(FLAG_IS_HUXLEY_RUNNING);
	deff_start (DEFF_HUXLEY_START_EFFECT);//under /kernel/deff.c
	task_sleep_sec (5);
	lamp_tristate_flash(LM_RETINA_SCAN);
	task_sleep_sec (2);
	lamp_tristate_off(LM_RETINA_SCAN);
	flasher_pulse (FLASH_EJECT_FLASHER);
	flasher_pulse (FLASH_EJECT_FLASHER);
	flasher_pulse (FLASH_EJECT_FLASHER);
	flasher_pulse (FLASH_EJECT_FLASHER);
	sol_request (SOL_EJECT); //request to fire the eject sol
}//end of function



//backwards shot to retina scan
void huxley_made(void){
	play_huxley_sounds();
	if (flag_test(FLAG_IS_HUXLEY_ENABLED) )	huxley_begin();
	else {
		score (HUXLEY_SCORE);
		deff_start (DEFF_HUXLEY_INFO_EFFECT);
		task_sleep (TIME_2S);
		lamp_tristate_flash(LM_RETINA_SCAN);
		task_sleep (TIME_2S);
		lamp_tristate_off(LM_RETINA_SCAN);
		flasher_pulse (FLASH_EJECT_FLASHER);
		flasher_pulse (FLASH_EJECT_FLASHER);
		flasher_pulse (FLASH_EJECT_FLASHER);
		flasher_pulse (FLASH_EJECT_FLASHER);
		sol_request (SOL_EJECT); //request to fire the eject sol
	}//end of else
}//end of function



 //shot made during huxley mode
void huxley_mode_shot_made(void) {
	++huxley_mode_shots_made;
	score (HUXLEY_MODE_HIT_SCORE);
	score_add (huxley_mode_score, score_table[HUXLEY_MODE_HIT_SCORE]);
	score_add (huxley_mode_score_total_score, score_table[HUXLEY_MODE_HIT_SCORE]);
	deff_start (DEFF_HUXLEY_HIT_EFFECT);//under /kernel/deff.c
}//end of function



/****************************************************************************
 * sound effects
 ****************************************************************************/
void play_huxley_sounds(void){
	U8 huxley_SoundCounter;
	huxley_SoundCounter = random_scaled(huxley_TotalNumOfSounds);//from kernal/random.c
	sound_start (ST_SPEECH, huxley_SoundsArray[huxley_SoundCounter], SL_4S, PRI_GAME_QUICK5);
}//end of function




/****************************************************************************
 * DMD display
 ****************************************************************************/
void huxley_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}




void huxley_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void huxley_frame_with_words_display_fipps_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_fipps, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void huxley_info_effect_deff(void) {
	dmd_alloc_pair_clean ();
	dmd_sched_transition (&trans_scroll_down);
	huxley_animation_display_effect (IMG_HUXLEY_B1_START, IMG_HUXLEY_B1_END);
	task_sleep_sec (1);
			dmd_clean_page_low ();
			dmd_sched_transition (&trans_scroll_down);
			font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_1, "START 4 NON-CLAW");
			font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_2, "MODES FOR");
			font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "HUXLEY");
			dmd_show_low();
			task_sleep_sec (2);
	dmd_alloc_pair_clean ();
	dmd_sched_transition (&trans_scroll_down);
	huxley_animation_display_effect (IMG_HUXLEY_B2_START, IMG_HUXLEY_B2_END);
	dmd_show2 ();
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff



	void huxley_start_effect_deff(void) {
	dmd_alloc_pair_clean ();
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Top, "LENINA");
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "HUXLEY");
	dmd_show_low();
	task_sleep_sec (2);

	play_huxley_sounds();

	dmd_sched_transition (&trans_scroll_down);
	dmd_alloc_pair_clean ();
	huxley_animation_display_effect (IMG_HUXLEY_A_START, IMG_HUXLEY_A_END);
	task_sleep_sec (1);

	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);

	dmd_sched_transition (&trans_scroll_down);
	dmd_alloc_pair_clean ();
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Top, "STANDUPS");
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "1 MILLION");
	dmd_show_low();
	task_sleep_sec (2);

	play_huxley_sounds();

	dmd_sched_transition (&trans_scroll_down);
	dmd_alloc_pair_clean ();
	huxley_animation_display_effect (IMG_HUXLEY_B1_START, IMG_HUXLEY_B1_END);
	task_sleep_sec (1);

	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);

	dmd_sched_transition (&trans_scroll_down);
	dmd_alloc_pair_clean ();
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Top, "REBOUNDS");
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "1 MILLION");
	dmd_show_low();
	task_sleep_sec (2);

	play_huxley_sounds();

	dmd_sched_transition (&trans_scroll_down);
	dmd_alloc_pair_clean ();
	huxley_animation_display_effect (IMG_HUXLEY_B2_START, IMG_HUXLEY_B2_END);
	task_sleep_sec (1);

	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);

	dmd_sched_transition (&trans_scroll_down);
	dmd_alloc_pair_clean ();
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Top, "ORBITS");
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "1 MILLION");
	dmd_show_low();
	task_sleep_sec (2);

	play_huxley_sounds();

	dmd_sched_transition (&trans_scroll_down);
	dmd_alloc_pair_clean ();
	huxley_animation_display_effect (IMG_HUXLEY_D_START, IMG_HUXLEY_D_END);
	task_sleep_sec (1);

	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);

	dmd_sched_transition (&trans_scroll_down);
	dmd_alloc_pair_clean ();
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Top, "RAMPS");
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "1 MILLION");
	dmd_show_low();
	task_sleep_sec (2);

	play_huxley_sounds();

	dmd_sched_transition (&trans_scroll_down);
	dmd_alloc_pair_clean ();
	huxley_animation_display_effect (IMG_HUXLEY_E_START, IMG_HUXLEY_E_END);
	task_sleep_sec (1);

	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK5);

	dmd_sched_transition (&trans_scroll_down);
	dmd_alloc_pair_clean ();
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Top, "SUBWAY");
	font_render_string_center (&font_fipps, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "1 MILLION");
	dmd_show_low();
	task_sleep_sec (2);

	deff_exit ();
}//end of mode_effect_deff



void huxley_hit_effect_deff(void) {
	U8 			huxley_MessageCounter;
	huxley_MessageCounter = random_scaled(5);
	dmd_clean_page_high ();//
	dmd_clean_page_low ();//

	sound_send (EXPLOSION1_SHORT);
	task_sleep (TIME_100MS);
	sound_send (EXPLOSION1_SHORT);
	task_sleep (TIME_100MS);
	sound_send (EXPLOSION1_SHORT);
	task_sleep (TIME_100MS);
	sound_send (EXPLOSION1_MED);
	task_sleep (TIME_100MS);
	sound_send (EXPLOSION1_LONG);
	task_sleep (TIME_100MS);

	play_huxley_sounds();

	switch (huxley_MessageCounter) {
		default:
		case 0:
			huxley_animation_display_effect (IMG_HUXLEY_A_START, IMG_HUXLEY_A_END);
			huxley_frame_with_words_display_fipps_effect (IMG_HUXLEY_A_END, DMD_MIDDLE_X - 30, DMD_BIG_CY_Bot, "HUXLEY");
			break;
		case 1:
			huxley_animation_display_effect (IMG_HUXLEY_B1_START, IMG_HUXLEY_B1_END);
			huxley_frame_with_words_display_fipps_effect (IMG_HUXLEY_B1_END, DMD_MIDDLE_X - 30, DMD_BIG_CY_Bot, "HUXLEY");
			break;
		case 2:
			huxley_animation_display_effect (IMG_HUXLEY_B2_START, IMG_HUXLEY_B2_END);
			huxley_frame_with_words_display_fipps_effect (IMG_HUXLEY_B2_END, DMD_MIDDLE_X - 30, DMD_BIG_CY_Bot, "HUXLEY");
			break;
		case 3:
			huxley_animation_display_effect (IMG_HUXLEY_D_START, IMG_HUXLEY_D_END);
			huxley_frame_with_words_display_fipps_effect (IMG_HUXLEY_D_END, DMD_MIDDLE_X + 30, DMD_BIG_CY_Bot, "HUXLEY");
			break;
		case 4:
			huxley_animation_display_effect (IMG_HUXLEY_E_START, IMG_HUXLEY_E_END);
			huxley_frame_with_words_display_fipps_effect (IMG_HUXLEY_E_END, DMD_MIDDLE_X - 30, DMD_BIG_CY_Bot, "HUXLEY");
			break;
		}//end of switch
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff



void huxley_effect_deff(void) {
	U8 frame = 0;
	U8 frame_counter = 0;
	for (;;) {
		//change the background every 5 seconds or so
		if (++frame_counter % 10 == 0) { if (frame >= 11) frame = 0; else frame ++; 	play_huxley_sounds(); }
		dmd_alloc_pair_clean();
		dmd_map_overlay ();
		dmd_clean_page_low ();
		dmd_draw_thin_border (dmd_low_buffer);
		sprintf ("%d", huxley_mode_timer);
		font_render_string_center (&font_var5, DMD_MIDDLE_X - 50, DMD_SMALL_CY_5, sprintf_buffer);
		font_render_string_center (&font_var5, DMD_MIDDLE_X + 50, DMD_SMALL_CY_5, sprintf_buffer);
		sprintf_score (huxley_mode_score);
		font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_5, sprintf_buffer);
		switch (frame) {
			case 0:	font_render_string_center (&font_fipps, DMD_MIDDLE_X + 35, DMD_BIG_CY_Top, "HUXLEY"); break; //ok
			case 2:	font_render_string_center (&font_fipps, DMD_MIDDLE_X + 35, DMD_BIG_CY_Bot, "HUXLEY"); break; //ok
			case 4:	font_render_string_center (&font_fipps, DMD_MIDDLE_X + 35, DMD_BIG_CY_Bot, "HUXLEY"); break; //ok
			case 6:	font_render_string_center (&font_fipps, DMD_MIDDLE_X + 35, DMD_BIG_CY_Bot, "HUXLEY"); break; //ok
			case 8:	font_render_string_center (&font_fipps, DMD_MIDDLE_X + 35, DMD_BIG_CY_Top, "HUXLEY"); break; //ok
			case 10: font_render_string_center (&font_fipps, DMD_MIDDLE_X - 35, DMD_BIG_CY_Top, "HUXLEY"); break; //ok
		}//end of switch
		dmd_text_outline ();
		dmd_alloc_pair ();
		switch (frame) {
			default:
			case 0:		frame_draw(IMG_HUXLEY_END_SCENE_START); break;
			case 1:		frame_draw(IMG_HUXLEY_END_SCENE_1); 	break;
			case 2:		frame_draw(IMG_HUXLEY_END_SCENE_2); 	break;
			case 3:		frame_draw(IMG_HUXLEY_END_SCENE_3); 	break;
			case 4:		frame_draw(IMG_HUXLEY_END_SCENE_4); 	break;
			case 5:		frame_draw(IMG_HUXLEY_END_SCENE_5); 	break;
			case 6:		frame_draw(IMG_HUXLEY_END_SCENE_6); 	break;
			case 7:		frame_draw(IMG_HUXLEY_END_SCENE_7); 	break;
			case 8:		frame_draw(IMG_HUXLEY_END_SCENE_8); 	break;
			case 9:		frame_draw(IMG_HUXLEY_END_SCENE_9); 	break;
			case 10:	frame_draw(IMG_HUXLEY_END_SCENE_10); 	break;
			case 11:	frame_draw(IMG_HUXLEY_END_SCENE_11); 	break;
		}//end of switch
		dmd_overlay_outline ();
		dmd_show2 ();
		task_sleep (TIME_500MS);
	}//END OF ENDLESS LOOP
}//end of mode_effect_deff



