/*
 * demolition man
 * museum.c
 * 
 * written by James Cardona
 *
 * handles the lock freezes and the trigger of multiballs
 *
 *
 * */
/* CALLSET_SECTION (museum, __machine3__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct

//local variables
score_t		museum_score;
U8			museum_jackpot_shots_made;
__boolean	museum_start_music;
U8 	museum_MessageCounter;

//external variables
extern U8			NumBallsFrozen; //from lock_freeze_mbstart.c

//internally called function prototypes  --external found at protos.h
void museum_player_reset (void);
void museum_jackpot_effect(void);

/****************************************************************************
 * multiball definition structure
 ***************************************************************************/
struct mb_mode_ops museum_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB,
	.deff_starting = DEFF_MUSEUM_START_EFFECT,
	.deff_running = DEFF_MUSEUM_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms
};
//task_gid_t gid_running;
//task_gid_t gid_in_grace;


/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void museum_player_reset (void) {
	flag_off(FLAG_IS_MUSEUM_MB_RUNNING);
	score_zero(museum_score);
	museum_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	museum_start_music = FALSE;
	museum_MessageCounter = 0;
}//end of function



CALLSET_ENTRY (museum, start_player) { museum_player_reset(); }



/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (museum, music_refresh)  {
	if (museum_start_music)				music_request (SPARKS, PRI_GAME_QUICK8);
	else 									mb_mode_music_refresh (&museum_mode);
}//end of function



CALLSET_ENTRY (museum, display_update) { mb_mode_display_update (&museum_mode); }



CALLSET_ENTRY (museum, end_ball) {
	if (flag_test(FLAG_IS_MUSEUM_MB_RUNNING)) {
		mb_mode_end_ball (&museum_mode);
		jackpot_reset();
		flag_off(FLAG_IS_MUSEUM_MB_RUNNING);
		if (flag_test(FLAG_IS_R_RAMP_CLAWREADY) ) 	rramp_clawready_on();
		else										rramp_clawready_off();
	}
}//end of function



//puts in grace period if set
CALLSET_ENTRY (museum, single_ball_play) {
	if (flag_test(FLAG_IS_MUSEUM_MB_RUNNING)) {
		mb_mode_end_ball (&museum_mode);
		jackpot_reset();
		flag_off(FLAG_IS_MUSEUM_MB_RUNNING);
		if (flag_test(FLAG_IS_R_RAMP_CLAWREADY) ) 	rramp_clawready_on();
		else										rramp_clawready_off();
	}
}//end of function



/****************************************************************************
 * body
 *
 ***************************************************************************/
void museum_start(void) {
	museum_start_music = TRUE; //for to play the helicopter instead of the music
	flag_on(FLAG_IS_MUSEUM_MB_RUNNING);
	mb_mode_start(&museum_mode);
	multiball_started();//reset all MB start criteria for next time
	deff_start (DEFF_MUSEUM_START_EFFECT);
	diverter_stop();//defined in divhold2.ct

	//LIGHTS
			lamp_tristate_flash(LM_MUSEUM_MULTIBALL);
			task_sleep (TIME_2S);
			lamp_tristate_on (LM_MUSEUM_MULTIBALL);
			lamp_tristate_off (LM_FREEZE_1);
			lamp_tristate_off (LM_FREEZE_2);
			lamp_tristate_off (LM_FREEZE_3);
			lamp_tristate_off (LM_FREEZE_4);


	//SOUNDS
			U8 	museum_SoundCounter;
			museum_SoundCounter = random_scaled(2);//from kernal/random.c - pick number from 0 to 2
			if (museum_SoundCounter == 0)
				sound_start (ST_SPEECH, SPCH_WHAT_YOU_DOING_HERE, SL_4S, PRI_GAME_QUICK5);
			else
				sound_start (ST_SPEECH, SPCH_GET_THIS_PARTNER, SL_4S, PRI_GAME_QUICK5);
	task_sleep (TIME_3S);
	museum_start_music = FALSE; //for to kill the music

	choose_random_jackpot();//randomize which jackpot shot to make
	//----------
	//serve balls
	//----------
//				serve_ball_auto(); //add one ball to the playfield - NOT technically a multiball since doesn't change global ball count
//				task_sleep (TIME_3S);
//				serve_ball_auto(); //add one ball to the playfield - NOT technically a multiball since doesn't change global ball count
//				task_sleep (TIME_3S);
				set_ball_count (3);  //this also works unless the number is > 2 then set_ball_count_task at serve.c breaks horribly
}//end of function



//jackpot shot
void museum_jackpot_made(void) {
	score_add (museum_score, score_table[MUSEUM_MB_SCORE]);
	score (MUSEUM_MB_SCORE);
	museum_jackpot_effect();//under /kernel/deff.c
}//end of function



/****************************************************************************
 * DMD display and sound effects
 ****************************************************************************/
void museum_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void museum_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}



void museum_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_steel, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void museum_start_effect_deff(void) {
	U8 			start_MessageCounter;
	start_MessageCounter = random_scaled(3);
	dmd_clean_page_high ();//
	dmd_clean_page_low ();//
	switch (start_MessageCounter) {
		default:
		case 0:
			museum_animation_display_effect (IMG_MUSEUM_D1_START, IMG_MUSEUM_D1_END);
			museum_frame_bitfade_fast(IMG_MUSEUM_D2_START);
			museum_animation_display_effect (IMG_MUSEUM_D2_START, IMG_MUSEUM_D2_END);
			museum_frame_bitfade_fast(IMG_SIMON_C_START);
			museum_animation_display_effect (IMG_SIMON_C_START, IMG_SIMON_C_END);
			dmd_map_overlay ();
			dmd_clean_page_low ();
			font_render_string_center (&font_steel, DMD_MIDDLE_X - 25, DMD_BIG_CY_Top, "MUSEUM");
			font_render_string_center (&font_steel, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "MULTIBALL");
			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(IMG_SIMON_C_END);
			dmd_overlay_outline ();
			dmd_show2 ();
			break;
		case 1:
			museum_animation_display_effect (IMG_MUSEUM_D1_START, IMG_MUSEUM_D1_END);
			museum_frame_bitfade_fast(IMG_MUSEUM_D2_START);
			museum_animation_display_effect (IMG_MUSEUM_D2_START, IMG_MUSEUM_D2_END);
			museum_frame_bitfade_fast(IMG_MUSEUM_D3_START);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			dmd_map_overlay ();
			dmd_clean_page_low ();
			font_render_string_center (&font_steel, DMD_MIDDLE_X - 25, DMD_BIG_CY_Top, "MUSEUM");
			font_render_string_center (&font_steel, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "MULTIBALL");
			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(IMG_MUSEUM_D3_END);
			dmd_overlay_outline ();
			dmd_show2 ();
			break;
		case 2:
			museum_animation_display_effect (IMG_MUSEUM_C1_START, IMG_MUSEUM_C1_END);
			museum_frame_bitfade_fast(IMG_MUSEUM_C2_START);
			museum_animation_display_effect (IMG_MUSEUM_C2_START, IMG_MUSEUM_C2_END);
			museum_frame_bitfade_fast(IMG_MUSEUM_D2_START);
			museum_animation_display_effect (IMG_MUSEUM_D2_START, IMG_MUSEUM_D2_END);
			museum_frame_bitfade_fast(IMG_SIMON_D_START);
			museum_animation_display_effect (IMG_SIMON_D_START, IMG_SIMON_D_END);
			dmd_map_overlay ();
			dmd_clean_page_low ();
			font_render_string_center (&font_steel, DMD_MIDDLE_X - 25, DMD_BIG_CY_Top, "MUSEUM");
			font_render_string_center (&font_steel, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "MULTIBALL");
			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(IMG_SIMON_D_END);
			dmd_overlay_outline ();
			dmd_show2 ();
			break;
	}//end of switch
	task_sleep_sec (2);
	deff_exit ();
}//end of mode_effect_deff



void museum_jackpot_sounds_task(void) {
	U8 			jackpot_sounds_MessageCounter;
	jackpot_sounds_MessageCounter = random_scaled(3);
	if (++museum_jackpot_shots_made % 2 == 0) {
			switch (jackpot_sounds_MessageCounter) {
				case 0: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_WES, SL_2S, PRI_GAME_QUICK5); break;
				case 1: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_SLY, SL_2S, PRI_GAME_QUICK5); break;
				case 2: 	sound_start (ST_SPEECH, SPCH_DOUBLE, SL_2S, PRI_GAME_QUICK5); break;
			}//end of switch
	}//end of if
	else {
		switch (jackpot_sounds_MessageCounter) {
			case 0: 	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK5); break;
			case 1: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK5); break;
			case 2: 	sound_start (ST_SPEECH, SPCH_UHHN, SL_2S, PRI_GAME_QUICK5); break;
		}//end of switch
	}//end of else
	task_sleep (TIME_500MS + TIME_300MS);
	sound_start (ST_EFFECT, SPARKS, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, SPARKS, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, SPARKS, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, ZAPP, SL_2S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, ZAPP, SL_2S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, ZAPP, SL_2S, PRI_GAME_QUICK5);
	task_sleep (TIME_500MS);
	task_exit();
}//end of mode_effect_deff



void museum_jackpot_effect(void) {
	deff_start (DEFF_MUSEUM_JACKPOT_EFFECT);
}//end of FUNCTION




void museum_jackpot_effect_deff(void) {
	//if (++museum_MessageCounter > 4) museum_MessageCounter = 0; // = random_scaled(6);
	museum_MessageCounter = random_scaled(7);
	dmd_clean_page_high ();//
	dmd_clean_page_low ();//

	task_create_gid1 (GID_MUSEUM_JACKPOT_SOUND, museum_jackpot_sounds_task);

	switch (museum_MessageCounter) {
		default:
		case 0:
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_frame_with_words_display_steel_effect (IMG_MUSEUM_D3_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 1:
			museum_animation_display_effect (IMG_MUSEUM_C2_START, IMG_MUSEUM_C2_END);
			museum_frame_with_words_display_steel_effect (IMG_MUSEUM_C2_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Top, "JACKPOT");
			break;
		case 2:
			museum_animation_display_effect (IMG_MUSEUM_C1_START, IMG_MUSEUM_C1_END);
			museum_frame_with_words_display_steel_effect (IMG_MUSEUM_C1_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 3:
			museum_animation_display_effect (IMG_FIGHT_A_START, IMG_FIGHT_A_END);
			museum_frame_with_words_display_steel_effect (IMG_FIGHT_A_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 4:
			museum_animation_display_effect (IMG_SIMON_D_START, IMG_SIMON_D_END);
			museum_frame_with_words_display_steel_effect (IMG_SIMON_D_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 5:
			museum_animation_display_effect (IMG_SIMON_C_START, IMG_SIMON_C_END);
			museum_frame_with_words_display_steel_effect (IMG_SIMON_C_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 6:
			museum_animation_display_effect (IMG_MUSEUM_D1_START, IMG_MUSEUM_D1_END);
			museum_animation_display_effect (IMG_MUSEUM_D2_START, IMG_MUSEUM_D2_END);
			museum_frame_with_words_display_steel_effect (IMG_MUSEUM_D2_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		}//end of switch
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff


//TODO: museum effect
	//the image is 4 color in 2 panes, so we must increment by 2's not 1's
	U8 museum_effect_deff_table[] = {	0, 2, 0, 2, 4, 2, 4, 2, 0, 0,
										2, 4, 6, 8, 6, 8, 4, 2, 0, 6,
										2, 6, 8, 4, 6, 8, 2, 0, 2, 0, 4, 2 };

	void museum_effect_deff (void) {
		U8 museum_display_counter = 0;
		__boolean TOGGLE = FALSE;

		dmd_alloc_pair_clean();

		for (;;) {
				dmd_map_overlay ();
				dmd_clean_page_low ();
				dmd_draw_thin_border (dmd_low_buffer);
				font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Top, "MUSEUM");
				if (museum_display_counter % 10 != 0) { //draw for 9/10 and blank for 1/10
							if (TOGGLE) 	sprintf ("15 MILLION");
							else 			sprintf ("JACKPOT LIT"); }
				else 						sprintf ("");

				font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Bot, sprintf_buffer);

				dmd_text_outline ();
				dmd_alloc_pair ();
				frame_draw(IMG_FORTRESS_RUN_0 + museum_effect_deff_table[museum_display_counter]);
				dmd_overlay_outline ();
				dmd_show2 ();
			task_sleep (TIME_200MS);

			museum_display_counter++;
			if (museum_display_counter >= 30) museum_display_counter  = 0;
			if (museum_display_counter % 10 == 0) { if (TOGGLE) TOGGLE = FALSE; else TOGGLE = TRUE; }//change TOGGLE once per second
		}//END OF ENDLESS LOOP
	}//end of function

