/*
 * demolition man
 * museum.c
 * 
 * written by James Cardona
 *
 * handles the lock freezes and the trigger of multiballs
 *
 *
 * */
/* CALLSET_SECTION (museum, __machine5__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct
#include "museum.h"

//local variables
score_t		museum_score;
U8			museum_jackpot_shots_made;
__boolean	museum_start_music;
U8 			museum_MessageCounter;
U8 museum_display_counter;
U8 MUS_TOGGLE;
__boolean	museum_ballsave;


//external variables
extern U8			NumBallsFrozen; //from lock_freeze_mbstart.c

//internally called function prototypes  --external found at protos.h
void museum_player_reset (void);



/****************************************************************************
 * multiball definition structure
 ***************************************************************************/
struct mb_mode_ops museum_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB,
	.deff_starting = DEFF_MUSEUM_START_EFFECT,
	.deff_running = DEFF_MUSEUM_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms
};
//task_gid_t gid_running;
//task_gid_t gid_in_grace;


/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void museum_player_reset (void) {
	flag_off(FLAG_IS_MUSEUM_MB_RUNNING);
	score_zero(museum_score);
	museum_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	museum_start_music = FALSE;
	museum_MessageCounter = 0;
}//end of function



CALLSET_ENTRY (museum, start_player) { museum_player_reset(); }



/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (museum, music_refresh)  {
//	if (museum_start_music)				music_request (SPARKS, PRI_GAME_QUICK8);
//	else 									mb_mode_music_refresh (&museum_mode);
	if (flag_test(FLAG_IS_MUSEUM_MB_RUNNING))	music_request (MUS_MB, PRI_GAME_QUICK7);
}//end of function



CALLSET_ENTRY (museum, display_update) {
	if (flag_test(FLAG_IS_MUSEUM_MB_RUNNING) )
			deff_start_bg (DEFF_MUSEUM_EFFECT, PRI_MULTIBALL);
}//end of function



CALLSET_ENTRY (museum, end_ball) {
	if (flag_test(FLAG_IS_MUSEUM_MB_RUNNING)) {
		mb_mode_end_ball (&museum_mode);
		jackpot_reset();
		end_super_jackpot_reminder();
		flag_off(FLAG_IS_MUSEUM_MB_RUNNING);
	}
}//end of function



//puts in grace period if set
CALLSET_ENTRY (museum, single_ball_play) {
	if (flag_test(FLAG_IS_MUSEUM_MB_RUNNING)) {
		mb_mode_end_ball (&museum_mode);
		end_super_jackpot_reminder();
		combo_init();
		diverter_check();

		//this acts as kind of a grace period for the jackpots
		task_sleep_sec(3);
		flag_off(FLAG_IS_MUSEUM_MB_RUNNING);
		jackpot_reset();
	}
}//end of function


//if a ball drains during the mode and with time still on the ballsave timer - send it back in play
CALLSET_BOOL_ENTRY (museum, ball_drain) { //thrown by device.c
	if	(flag_test(FLAG_IS_MUSEUM_MB_RUNNING)
		&& museum_ballsave)	{
		sound_start (ST_SPEECH, SPCH_UHHN, SL_2S, PRI_GAME_QUICK5);
		serve_ball_auto ();
		return FALSE; //this is not a valid drain, don't count it
	}
	else return TRUE; //this is a valid drain
}//end of callset







/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
void museum_ballsave_task (void) {
	task_sleep_sec(15);
	museum_ballsave = FALSE;
	task_exit();
}//end of function



void museum_start_sounds (void) {
	U8 i;
	for(i = 0; i < 6; i++) {
		sound_start (ST_ANY, SPARKS, SL_1S, PRI_GAME_QUICK5);
		task_sleep (TIME_500MS);
	}
	task_exit();
}//end of function



void museum_start(U8 num) {
	kill_combos();
//	museum_start_music = TRUE; //for to play the helicopter instead of the music
	task_create_gid1 (GID_MUSEUM_START_NOISE, museum_start_sounds);
	flag_on(FLAG_IS_MUSEUM_MB_RUNNING);
	museum_ballsave = TRUE;
	mb_mode_start(&museum_mode);

	score_add (museum_score, score_table[MUSEUM_MB_SCORE]);
	score (MUSEUM_MB_SCORE);

	museum_display_counter = 0;
	MUS_TOGGLE = 0;
	multiball_started();//reset all MB start criteria for next time
	deff_start (DEFF_MUSEUM_START_EFFECT);
	diverter_stop();//defined in divhold2.ct
	task_kill_gid (GID_CR_LIGHTS);

	//LIGHTS
			lamp_tristate_flash(LM_MUSEUM_MULTIBALL);
			task_sleep (TIME_2S);
			lamp_tristate_on (LM_MUSEUM_MULTIBALL);
			lamp_tristate_off (LM_FREEZE_1);
			lamp_tristate_off (LM_FREEZE_2);
			lamp_tristate_off (LM_FREEZE_3);
			lamp_tristate_off (LM_FREEZE_4);

	//SOUNDS
			U8 	museum_SoundCounter;
			museum_SoundCounter = random_scaled(2);//from kernal/random.c - pick number from 0 to 2
			if (museum_SoundCounter == 0)
				sound_start (ST_SPEECH, SPCH_WHAT_YOU_DOING_HERE, SL_4S, PRI_GAME_QUICK5);
			else
				sound_start (ST_SPEECH, SPCH_GET_THIS_PARTNER, SL_4S, PRI_GAME_QUICK5);
	task_sleep (TIME_3S);
	museum_start_music = FALSE; //for to kill the music

	//serve balls
//	set_ball_count (3);
	if (num >= 4) set_ball_count (5);
	else set_ball_count (num + 1);

	task_create_gid1 (GID_MUSEUM_BALL_SAVE, museum_ballsave_task);
	task_sleep (TIME_3S);
	choose_multiple_random_jackpot(2);
}//end of function



//jackpot shot
void museum_jackpot_made(void) {
	score_add (museum_score, score_table[MUSEUM_JP_MB_SCORE]);
	score (MUSEUM_JP_MB_SCORE);
	deff_start (DEFF_MUSEUM_JACKPOT_EFFECT);
	choose_multiple_random_jackpot(2); //switch which shots are jackpot shots

	if (IN_TEST) {	start_super_jackpot_reminder(); }
	else			if (museum_jackpot_shots_made % 5 == 0) 	start_super_jackpot_reminder();
}//end of function



void museum_award_super_jackpot(void) {
	score_add (museum_score, score_table[MUSEUM_SUPER_JP_MB_SCORE]);
	score (MUSEUM_SUPER_JP_MB_SCORE);
	deff_start(DEFF_MUSEUM_SUPER_JACKPOT);
}//end of function




/****************************************************************************
 *
 * display effects
 *
 ****************************************************************************/
void museum_super_jackpot_deff (void) {
	U8 i;

	/* Flash Jackpot */
	for (i = 0; i < 3; i++) {
		switch (i) {
		case 0: sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK5); break;
		case 1: sound_start (ST_SPEECH, SPCH_YOU_GOT_IT, SL_2S, PRI_GAME_QUICK5); break;
		case 2: sound_start (ST_SPEECH, SPCH_WHO_IS_THAT, SL_2S, PRI_GAME_QUICK5);
		}//end of switch
		dmd_alloc_pair ();
		frame_draw (IMG_JACKPOT_END - 2);
		dmd_show2 ();
		sample_start (MACHINE10, SL_100MS);
		task_sleep (TIME_200MS);

		dmd_alloc_pair ();
		frame_draw (IMG_JACKPOT_END);
		dmd_show2 ();
		sample_start (MACHINE10, SL_100MS);
		task_sleep (TIME_500MS);

		dmd_alloc_pair ();
		frame_draw (IMG_JACKPOT_END - 2);
		dmd_show2 ();
		sample_start (MACHINE10, SL_100MS);
		task_sleep (TIME_500MS);

		dmd_alloc_pair ();
		frame_draw (IMG_JACKPOT_END);
		dmd_show2 ();
		sample_start (MACHINE10, SL_100MS);
		task_sleep (TIME_500MS);
	}//end of loop

	sample_start (MACHINE14_LONG, SL_1S);
	task_sleep (TIME_500MS);
	speech_start (SPCH_SUPER_JACKPOT, SL_1S);
	task_sleep_sec (1);

	deff_exit ();
}//end of function




void museum_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void museum_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}



void museum_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_1, "MUSEUM");
	font_render_string_center (&font_steel, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void museum_start_effect_deff(void) {
	U8 			start_MessageCounter;
	start_MessageCounter = random_scaled(3);
	dmd_clean_page_high ();//
	dmd_clean_page_low ();//
	switch (start_MessageCounter) {
		default:
		case 0:
			museum_animation_display_effect (IMG_MUSEUM_D1_START, IMG_MUSEUM_D1_END);
			museum_frame_bitfade_fast(IMG_MUSEUM_D2_START);
			museum_animation_display_effect (IMG_MUSEUM_D2_START, IMG_MUSEUM_D2_END);
			museum_frame_bitfade_fast(IMG_SIMON_C_START);
			museum_animation_display_effect (IMG_SIMON_C_START, IMG_SIMON_C_END);
			dmd_map_overlay ();
			dmd_clean_page_low ();
			font_render_string_center (&font_steel, DMD_MIDDLE_X - 25, DMD_BIG_CY_Top, "MUSEUM");
			font_render_string_center (&font_steel, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "MULTIBALL");
			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(IMG_SIMON_C_END);
			dmd_overlay_outline ();
			dmd_show2 ();
			break;
		case 1:
			museum_animation_display_effect (IMG_MUSEUM_D1_START, IMG_MUSEUM_D1_END);
			museum_frame_bitfade_fast(IMG_MUSEUM_D2_START);
			museum_animation_display_effect (IMG_MUSEUM_D2_START, IMG_MUSEUM_D2_END);
			museum_frame_bitfade_fast(IMG_MUSEUM_D3_START);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			dmd_map_overlay ();
			dmd_clean_page_low ();
			font_render_string_center (&font_steel, DMD_MIDDLE_X - 25, DMD_BIG_CY_Top, "MUSEUM");
			font_render_string_center (&font_steel, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "MULTIBALL");
			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(IMG_MUSEUM_D3_END);
			dmd_overlay_outline ();
			dmd_show2 ();
			break;
		case 2:
			museum_animation_display_effect (IMG_MUSEUM_C2_START, IMG_MUSEUM_C2_END);
			museum_frame_bitfade_fast(IMG_MUSEUM_D2_START);
			museum_animation_display_effect (IMG_MUSEUM_D2_START, IMG_MUSEUM_D2_END);
			dmd_map_overlay ();
			dmd_clean_page_low ();
			font_render_string_center (&font_steel, DMD_MIDDLE_X - 25, DMD_BIG_CY_Top, "MUSEUM");
			font_render_string_center (&font_steel, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "MULTIBALL");
			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(IMG_MUSEUM_D2_END);
			dmd_overlay_outline ();
			dmd_show2 ();
			break;
	}//end of switch
	task_sleep_sec (2);
	deff_exit ();
}//end of mode_effect_deff



void museum_jackpot_sounds_task(void) {
	U8 			jackpot_sounds_MessageCounter;
	jackpot_sounds_MessageCounter = random_scaled(3);
	if (++museum_jackpot_shots_made % 2 == 0) {
			switch (jackpot_sounds_MessageCounter) {
				case 0: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_WES, SL_2S, PRI_GAME_QUICK5); break;
				case 1: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_SLY, SL_2S, PRI_GAME_QUICK5); break;
				case 2: 	sound_start (ST_SPEECH, SPCH_DOUBLE, SL_2S, PRI_GAME_QUICK5); break;
			}//end of switch
	}//end of if
	else {
		switch (jackpot_sounds_MessageCounter) {
			case 0: 	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK5); break;
			case 1: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK5); break;
			case 2: 	sound_start (ST_SPEECH, SPCH_UHHN, SL_2S, PRI_GAME_QUICK5); break;
		}//end of switch
	}//end of else
	task_sleep (TIME_500MS + TIME_300MS);
	sound_start (ST_EFFECT, SPARKS, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, SPARKS, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, SPARKS, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, ZAPP, SL_2S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, ZAPP, SL_2S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, ZAPP, SL_2S, PRI_GAME_QUICK5);
	task_sleep (TIME_500MS);
	task_exit();
}//end of mode_effect_deff





void museum_jackpot_effect_deff(void) {
//	if (++museum_MessageCounter > 4) museum_MessageCounter = 0; // = random_scaled(6);
	museum_MessageCounter = random_scaled(5);
	dmd_clean_page_high ();//
	dmd_clean_page_low ();//

	task_create_gid1 (GID_MUSEUM_JACKPOT_SOUND, museum_jackpot_sounds_task);

	switch (museum_MessageCounter) {
		default:
		case 0:
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_animation_display_effect (IMG_MUSEUM_D3_START, IMG_MUSEUM_D3_END);
			museum_frame_with_words_display_steel_effect (IMG_MUSEUM_D3_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 1:
			museum_animation_display_effect (IMG_MUSEUM_C2_START, IMG_MUSEUM_C2_END);
			museum_frame_with_words_display_steel_effect (IMG_MUSEUM_C2_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 2:
			museum_animation_display_effect (IMG_FIGHT_A_START, IMG_FIGHT_A_END);
			museum_frame_with_words_display_steel_effect (IMG_FIGHT_A_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 3:
			museum_animation_display_effect (IMG_SIMON_C_START, IMG_SIMON_C_END);
			museum_frame_with_words_display_steel_effect (IMG_SIMON_C_END, DMD_MIDDLE_X - 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 4:
			museum_animation_display_effect (IMG_MUSEUM_D1_START, IMG_MUSEUM_D1_END);
			museum_animation_display_effect (IMG_MUSEUM_D2_START, IMG_MUSEUM_D2_END);
			museum_frame_with_words_display_steel_effect (IMG_MUSEUM_D2_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		}//end of switch
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff



void show_sparkle (void) {
U8 i;
	for (i = 0; i < 5; i++) {
		dmd_dup_mapped ();//allocate new space but make it a copy of what is on DMD now
		dmd_overlay_onto_color ();//mono overlay onto current color page

	//right side sparkles
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (museum_spark_right_1_bits, 115, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_right_1_bits, 115, 1); break;
			case 1: 	bitmap_blit (museum_spark_right_2_bits, 115, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_right_2_bits, 115, 1); break;
			case 2: 	bitmap_blit (museum_spark_right_3_bits, 115, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_right_3_bits, 115, 1); break;
			case 3: 	bitmap_blit (museum_spark_right_4_bits, 115, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_right_4_bits, 115, 1); break;
			case 4: 	bitmap_blit (museum_spark_right_5_bits, 115, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_right_5_bits, 115, 1); break;
			case 5: 	bitmap_blit (museum_spark_right_6_bits, 115, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_right_6_bits, 115, 1); break;
			case 6: 	bitmap_blit (museum_spark_right_7_bits, 115, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_right_7_bits, 115, 1); break;
			case 7: 	bitmap_blit (museum_spark_right_8_bits, 115, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_right_8_bits, 115, 1); break;
		}//end of case

		//left side sparkles
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (museum_spark_left_1_bits, 7, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_left_1_bits, 7, 1); break;
			case 1: 	bitmap_blit (museum_spark_left_2_bits, 7, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_left_2_bits, 7, 1); break;
			case 2: 	bitmap_blit (museum_spark_left_3_bits, 7, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_left_3_bits, 7, 1); break;
			case 3: 	bitmap_blit (museum_spark_left_4_bits, 7, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_left_4_bits, 7, 1); break;
			case 4: 	bitmap_blit (museum_spark_left_5_bits, 7, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_left_5_bits, 7, 1); break;
			case 5: 	bitmap_blit (museum_spark_left_6_bits, 7, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_left_6_bits, 7, 1); break;
			case 6: 	bitmap_blit (museum_spark_left_7_bits, 7, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_left_7_bits, 7, 1); break;
			case 7: 	bitmap_blit (museum_spark_left_8_bits, 7, 0); dmd_flip_low_high (); bitmap_blit (museum_spark_left_8_bits, 7, 1); break;
		}//end of case

		dmd_show2 ();//shows a 4 color image
		task_sleep (TIME_300MS);
		dmd_map_overlay ();/** Map a consecutive display page pair into windows 0 & 1 */
	}//end of loop
	dmd_alloc_pair_clean ();
}//end of func




void museum_effect_deff (void) {
	for (;;) {
		dmd_map_overlay ();
		dmd_clean_page_high ();
		dmd_clean_page_low ();
		dmd_draw_thin_border (dmd_low_buffer);

		bitmap_blit (museum_up_left_bits, 0, 2); //8x16
		bitmap_blit (museum_up_right_bits, 123, 2); //8x16

		bitmap_blit (museum_bot_left_bits, 0, 20); //24x10
		bitmap_blit (museum_bot_right_bits, 108, 20); //24x10

			font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Top - 2, "MUSEUM");

			sprintf_score(current_score);
			font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_3, sprintf_buffer);

				if (MUS_TOGGLE == 0) 		{ sprintf ("15 MILLION"); font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Bot, sprintf_buffer); }
				else if (MUS_TOGGLE == 1)	{ sprintf ("JACKPOT LIT"); font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Bot, sprintf_buffer); }
				else if (MUS_TOGGLE == 2)	{
											sprintf ("%d JACKPOTS MADE", museum_jackpot_shots_made);
											font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_4, sprintf_buffer);

											if (flag_test(FLAG_IS_SUPER_JACKPOT_ACTIVATED) )	sprintf ("SUPER JACKPOT LIT");
											else 												sprintf ("SHOOT %d TO LIGHT SUPER", 5 - (museum_jackpot_shots_made % 5) );
											font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_5, sprintf_buffer);
				}//end of else if (MUS_TOGGLE == 2)

			show_sparkle();  // takes approx 1.5 seconds
			if (++museum_display_counter % 4 == 0) { if (++MUS_TOGGLE > 2) MUS_TOGGLE = 0; } //change MUS_TOGGLE once per second
	}//END OF ENDLESS LOOP
	deff_exit();
}//end of function

