/*
 * demolition man
 * wasteland.c
 * 
 * written by James Cardona
 *
 * handles the lock freezes and the trigger of multiballs
 *
 *
 * */
/* CALLSET_SECTION (wasteland, __machine4__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct
#include "wasteland.h"

//local variables
score_t		wasteland_score;
U8			wasteland_jackpot_shots_made;
U8			wasteland_MessageCounter;
__boolean	wasteland_start_music;
U8 wasteland_display_counter;
U8 WL_TOGGLE;
__boolean	wasteland_ballsave;


//external variables
extern U8			NumBallsFrozen; //from lock_freeze_mbstart.c

//internally called function prototypes  --external found at protos.h
void wasteland_player_reset (void);



/****************************************************************************
 * multiball definition structure
 ***************************************************************************/
struct mb_mode_ops wasteland_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB,
	.deff_starting = DEFF_WASTELAND_START_EFFECT,
	.deff_running = DEFF_WASTELAND_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms
};
//task_gid_t gid_running;
//task_gid_t gid_in_grace;



/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void wasteland_player_reset (void) {
	flag_off(FLAG_IS_WASTELAND_MB_RUNNING);
	score_zero(wasteland_score);
	wasteland_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	wasteland_start_music = FALSE;
}//end of function



CALLSET_ENTRY (wasteland, start_player) { wasteland_player_reset(); }



/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (wasteland, music_refresh)  {
//	if (wasteland_start_music)				music_request (GROUND_HUMM, PRI_GAME_QUICK8);
//	else 									mb_mode_music_refresh (&wasteland_mode);
	if (flag_test(FLAG_IS_WASTELAND_MB_RUNNING))	music_request (MUS_MB, PRI_GAME_QUICK7);
}//end of function



CALLSET_ENTRY (wasteland, display_update) {
	if (flag_test(FLAG_IS_WASTELAND_MB_RUNNING))
			deff_start_bg (DEFF_WASTELAND_EFFECT, PRI_MULTIBALL);
}//end of function



CALLSET_ENTRY (wasteland, end_ball) {
	if (flag_test(FLAG_IS_WASTELAND_MB_RUNNING)) {
		mb_mode_end_ball (&wasteland_mode);
		jackpot_reset();
		end_super_jackpot_reminder();
		flag_off(FLAG_IS_WASTELAND_MB_RUNNING);
	}
}//end of function



//puts in grace period if set
CALLSET_ENTRY (wasteland, single_ball_play) {
	if (flag_test(FLAG_IS_WASTELAND_MB_RUNNING)) {
//		mb_mode_single_ball (&wasteland_mode);
		mb_mode_end_ball (&wasteland_mode);
		end_super_jackpot_reminder();
		combo_init();
		diverter_check();

		//this acts as kind of a grace period for the jackpots
		task_sleep_sec(3);
		flag_off(FLAG_IS_WASTELAND_MB_RUNNING);
		jackpot_reset();
	}
}//end of function



//if a ball drains during the mode and with time still on the ballsave timer - send it back in play
CALLSET_BOOL_ENTRY (wasteland, ball_drain) { //thrown by device.c
	if	(flag_test(FLAG_IS_WASTELAND_MB_RUNNING)
		&& wasteland_ballsave)	{
		sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK5);
		serve_ball_auto ();
		return FALSE; //this is not a valid drain, don't count it
	}
	else return TRUE; //this is a valid drain
}//end of callset








/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
void wasteland_ballsave_task (void) {
	task_sleep_sec(15);
	wasteland_ballsave = FALSE;
	task_exit();
}//end of function




void wasteland_start_sounds (void) {
	U8 i;
	for(i = 0; i < 6; i++) {
		sound_start (ST_ANY, SIREN, SL_1S, PRI_GAME_QUICK5);
		task_sleep (TIME_500MS);
	}
	task_exit();
}//end of function





void wasteland_start(U8 num) {
	kill_combos();
//	wasteland_start_music = TRUE; //for to play the helicopter instead of the music
	task_create_gid1 (GID_WASTELAND_START_NOISE, wasteland_start_sounds);
	flag_on(FLAG_IS_WASTELAND_MB_RUNNING);
	mb_mode_start(&wasteland_mode);

	score_add (wasteland_score, score_table[WASTELAND_MB_SCORE]);
	score (WASTELAND_MB_SCORE);

	wasteland_display_counter = 0;
	WL_TOGGLE = 0;
	wasteland_ballsave = TRUE;

	multiball_started();//reset all MB start criteria for next time
	deff_start (DEFF_WASTELAND_START_EFFECT);
	diverter_stop();//defined in divhold2.ct
	task_kill_gid (GID_CR_LIGHTS);

	//LIGHTS
			lamp_tristate_flash(LM_WASTELAND_MULTIBALL);
			task_sleep (TIME_2S);
			lamp_tristate_on (LM_WASTELAND_MULTIBALL);
			lamp_tristate_off (LM_FREEZE_1);
			lamp_tristate_off (LM_FREEZE_2);
			lamp_tristate_off (LM_FREEZE_3);
			lamp_tristate_off (LM_FREEZE_4);

	//SOUNDS
			U8 	wasteland_SoundCounter;
			wasteland_SoundCounter = random_scaled(2);//from kernal/random.c - pick number from 0 to 2
			if (wasteland_SoundCounter == 0)
				sound_start (ST_SPEECH, SPCH_IN_THIS_CENTURY, SL_4S, PRI_GAME_QUICK5);
			else
				sound_start (ST_SPEECH, SPCH_FEEL_GOOD_TOO, SL_4S, PRI_GAME_QUICK5);
	task_sleep (TIME_3S);
	wasteland_start_music = FALSE; //for to kill the music

	//serve balls
//	set_ball_count (4);
	if (num >= 4) set_ball_count (5);
	else set_ball_count (4);
	task_create_gid1 (GID_WASTELAND_BALL_SAVE, wasteland_ballsave_task);

	task_sleep (TIME_3S);
	set_all_jackpots(); //all 6 lit
}//end of function



//jackpot shot
void wasteland_jackpot_made(void) {
	score_add (wasteland_score, score_table[WASTELAND_JP_MB_SCORE]);
	score (WASTELAND_JP_MB_SCORE);
	deff_start (DEFF_WASTELAND_JACKPOT_EFFECT);
	choose_multiple_random_jackpot(3);

	if (IN_TEST) {	start_super_jackpot_reminder(); }
	else			if (wasteland_jackpot_shots_made % 5 == 0) 	start_super_jackpot_reminder();
}//end of function





void wasteland_award_super_jackpot(void) {
	score_add (wasteland_score, score_table[WASTELAND_SUPER_JP_MB_SCORE]);
	score (WASTELAND_SUPER_JP_MB_SCORE);
	deff_start(DEFF_WASTELAND_SUPER_JACKPOT);
}//end of function





/****************************************************************************
 *
 * display effects
 *
 ****************************************************************************/
void wasteland_super_jackpot_deff (void) {
	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK5);
	dmd_alloc_pair ();
	dmd_clean_page_low ();
	font_render_string_center (&font_lithograph, 64, 8, "SUPER");
	font_render_string_center (&font_lithograph, 64, 24, "JACKPOT");
	dmd_copy_low_to_high ();
	dmd_show_low ();
	dmd_invert_page (dmd_low_buffer);
	deff_swap_low_high (1, TIME_100MS);
	sound_start (ST_ANY, EXPLOSION1_SHORT, SL_2S, PRI_GAME_QUICK5);

	deff_swap_low_high (6, TIME_100MS);
	sound_start (ST_SPEECH, SPCH_HURRY, SL_2S, PRI_GAME_QUICK5);

	deff_swap_low_high (6, TIME_100MS);
	sound_start (ST_ANY, EXPLOSION1_SHORT, SL_2S, PRI_GAME_QUICK5);

	deff_swap_low_high (6, TIME_100MS);
	sound_start (ST_SPEECH, SPCH_COWS, SL_2S, PRI_GAME_QUICK5);

	deff_swap_low_high (6, TIME_100MS);
	sample_start (MACHINE14_LONG, SL_1S);
	task_sleep (TIME_500MS);

	speech_start (SPCH_SUPER_JACKPOT, SL_1S);
	task_sleep_sec (1);
	deff_exit ();
}//end of function




void wasteland_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}


void wasteland_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_1, "WASTELAND");
	font_render_string_center (&font_steel, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void wasteland_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}





void wasteland_start_effect_deff(void) {
	U16 fno;
	dmd_clean_page_high ();//
	dmd_clean_page_low ();//
	for (fno = IMG_WASTELAND_A1_START; fno <= IMG_WASTELAND_A1_END; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop

	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(IMG_WASTELAND_A2_START);
	dmd_show2 ();
	task_sleep (TIME_100MS);


	for (fno = IMG_WASTELAND_A2_START; fno <= IMG_WASTELAND_A2_END; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop

	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(IMG_WASTELAND_A3_START);
	dmd_show2 ();
	task_sleep (TIME_100MS);


	dmd_alloc_pair_clean ();// Clean both pages
	for (fno = IMG_WASTELAND_A3_START; fno <= IMG_WASTELAND_A3_END; fno += 2) {
		dmd_map_overlay ();
		dmd_clean_page_low ();
		font_render_string_center (&font_steel, DMD_MIDDLE_X + 10, DMD_BIG_CY_Bot, "WASTELAND");
		dmd_text_outline ();
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_overlay_outline ();
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
	task_sleep_sec (2);
		deff_exit ();
}//end of mode_effect_deff



void wasteland_jackpot_sounds_task(void) {
	U8 			wasteland_MessageCounter;
	wasteland_MessageCounter = random_scaled(3);
	if (++wasteland_jackpot_shots_made % 2 == 0) {
			switch (wasteland_MessageCounter) {
				case 0: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_WES, SL_2S, PRI_GAME_QUICK5); break;
				case 1: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_SLY, SL_2S, PRI_GAME_QUICK5); break;
				case 2: 	sound_start (ST_SPEECH, SPCH_DOUBLE, SL_2S, PRI_GAME_QUICK5); break;
			}//end of switch
	}//end of if
	else {
		switch (wasteland_MessageCounter) {
			case 0: 	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK5); break;
			case 1: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK5); break;
			case 2: 	sound_start (ST_SPEECH, SPCH_UHHN, SL_2S, PRI_GAME_QUICK5); break;
		}//end of switch
	}//end of else
	task_sleep (TIME_500MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_LONG, SL_2S, PRI_GAME_QUICK5);
	task_sleep (TIME_500MS);
	task_exit();
}//end of mode_effect_deff





U8 			wasteland_MessageCounter;
void wasteland_jackpot_effect_deff(void) {
//	if (++wasteland_MessageCounter > 3) wasteland_MessageCounter = 0;
	wasteland_MessageCounter = random_scaled(4);
	dmd_alloc_pair_clean ();

	task_create_gid1 (GID_WASTELAND_JACKPOT_SOUND, wasteland_jackpot_sounds_task);

	switch (wasteland_MessageCounter) {
		default:
		case 0:
			wasteland_animation_display_effect (IMG_WASTELAND_A2_START, IMG_WASTELAND_A2_END);
			wasteland_frame_with_words_display_steel_effect (IMG_WASTELAND_A2_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 1:
			wasteland_animation_display_effect (IMG_WASTELAND_A3_START, IMG_WASTELAND_A3_END);
			wasteland_frame_with_words_display_steel_effect (IMG_WASTELAND_A3_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 2:
			wasteland_animation_display_effect (IMG_WASTELAND_A1_START, IMG_WASTELAND_A1_END);
			wasteland_frame_with_words_display_steel_effect (IMG_WASTELAND_A1_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 3:
			wasteland_animation_display_effect (IMG_FLYKICK_A_START, IMG_FLYKICK_A_END);
			wasteland_frame_with_words_display_steel_effect (IMG_FLYKICK_A_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		}//end of switch
		task_sleep_sec (2);
		deff_exit ();
}//end of mode_effect_deff







void show_drips (void) {
		dmd_dup_mapped ();//allocate new space but make it a copy of what is on DMD now
		dmd_overlay_onto_color ();//mono overlay onto current color page

		//right side drips
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_drip1_bits, 123, 27); break;
			case 1: 	bitmap_blit (wasteland_drip2_bits, 124, 27); break;
			case 2: 	bitmap_blit (wasteland_drip3_bits, 123, 27); break;
			case 3: 	bitmap_blit (wasteland_drip4_bits, 124, 27); break;
		}//end of case

 	 	 //left side drips top
		 switch (random_scaled(8)) {
			case 3: 	bitmap_blit (wasteland_drip1_bits, 25, 16); break;
			case 4: 	bitmap_blit (wasteland_drip2_bits, 25, 16); break;
			case 5: 	bitmap_blit (wasteland_drip3_bits, 25, 16); break;
			case 6: 	bitmap_blit (wasteland_drip4_bits, 25, 16); break;
		}//end of case

 	 	 //left side drips bottom #1
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_drip1_bits, 17, 23); break;
			case 1: 	bitmap_blit (wasteland_drip2_bits, 17, 23); break;
			case 6: 	bitmap_blit (wasteland_drip3_bits, 17, 23); break;
			case 7: 	bitmap_blit (wasteland_drip4_bits, 17, 23); break;
		}//end of case

 	 	 //left side drips bottom #2
		 switch (random_scaled(16)) {
			case 2: 	bitmap_blit (wasteland_drip1_bits, 23, 24); break;
			case 3: 	bitmap_blit (wasteland_drip2_bits, 23, 24); break;
			case 4: 	bitmap_blit (wasteland_drip3_bits, 23, 24); break;
			case 5: 	bitmap_blit (wasteland_drip4_bits, 23, 24); break;
		}//end of case

 	 	 //right side steam #1
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_steam1_bits, 102, 5); break;
			case 1: 	bitmap_blit (wasteland_steam2_bits, 103, 4); break;
			case 2: 	bitmap_blit (wasteland_steam3_bits, 104, 5); break;
			case 3: 	bitmap_blit (wasteland_steam4_bits, 102, 3); break;
		}//end of case

 	 	 //right side steam #2
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_steam1_bits, 109, 5); break;
			case 1: 	bitmap_blit (wasteland_steam2_bits, 110, 4); break;
			case 2: 	bitmap_blit (wasteland_steam3_bits, 109, 5); break;
			case 3: 	bitmap_blit (wasteland_steam4_bits, 110, 3); break;
		}//end of case

 	 	 //right side steam #3
		 switch (random_scaled(16)) {
			case 0: 	bitmap_blit (wasteland_steam1_bits, 116, 3); break;
			case 1: 	bitmap_blit (wasteland_steam2_bits, 115, 4); break;
			case 2: 	bitmap_blit (wasteland_steam3_bits, 116, 2); break;
			case 3: 	bitmap_blit (wasteland_steam4_bits, 115, 3); break;
		}//end of case

 	 	 //right side steam #4
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_steam1_bits, 97, 5); break;
			case 1: 	bitmap_blit (wasteland_steam2_bits, 98, 4); break;
			case 2: 	bitmap_blit (wasteland_steam3_bits, 97, 5); break;
			case 3: 	bitmap_blit (wasteland_steam4_bits, 98, 3); break;
		}//end of case

	 	 //right side steam #5
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_steam1_bits, 122, 13); break;
			case 1: 	bitmap_blit (wasteland_steam2_bits, 121, 12); break;
			case 2: 	bitmap_blit (wasteland_steam3_bits, 122, 12); break;
			case 3: 	bitmap_blit (wasteland_steam4_bits, 121, 13); break;
		}//end of case

 	 	 //right side steam #6
		 switch (random_scaled(12)) {
			case 0: 	bitmap_blit (wasteland_steam1_bits, 126, 9); break;
			case 1: 	bitmap_blit (wasteland_steam2_bits, 126, 9); break;
			case 2: 	bitmap_blit (wasteland_steam3_bits, 125, 8); break;
			case 3: 	bitmap_blit (wasteland_steam4_bits, 125, 9); break;
		}//end of case

		 dmd_flip_low_high ();

		 //right side drips
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_drip1_bits, 122, 26); break;
			case 1: 	bitmap_blit (wasteland_drip2_bits, 123, 25); break;
			case 2: 	bitmap_blit (wasteland_drip3_bits, 124, 24); break;
			case 3: 	bitmap_blit (wasteland_drip4_bits, 125, 26); break;
		}//end of case

		 //left side drips top
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_drip1_bits, 25, 15); break;
			case 1: 	bitmap_blit (wasteland_drip2_bits, 25, 15); break;
			case 2: 	bitmap_blit (wasteland_drip3_bits, 25, 15); break;
			case 3: 	bitmap_blit (wasteland_drip4_bits, 25, 15); break;
		}//end of case

		 //left side drips bottom #1
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_drip1_bits, 16, 22); break;
			case 1: 	bitmap_blit (wasteland_drip2_bits, 17, 22); break;
			case 2: 	bitmap_blit (wasteland_drip3_bits, 16, 22); break;
			case 3: 	bitmap_blit (wasteland_drip4_bits, 17, 22); break;
		}//end of case

		 //left side drips bottom #2
		 switch (random_scaled(16)) {
			case 0: 	bitmap_blit (wasteland_drip1_bits, 22, 23); break;
			case 1: 	bitmap_blit (wasteland_drip2_bits, 23, 23); break;
			case 2: 	bitmap_blit (wasteland_drip3_bits, 24, 23); break;
			case 3: 	bitmap_blit (wasteland_drip4_bits, 23, 23); break;
		}//end of case

 	 	 //right side steam #1
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_steam1_bits, 102, 5); break;
			case 1: 	bitmap_blit (wasteland_steam2_bits, 103, 3); break;
			case 2: 	bitmap_blit (wasteland_steam3_bits, 102, 5); break;
			case 3: 	bitmap_blit (wasteland_steam4_bits, 103, 4); break;
		}//end of case

 	 	 //right side steam #2
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_steam2_bits, 109, 5); break;
			case 1: 	bitmap_blit (wasteland_steam1_bits, 110, 4); break;
			case 2: 	bitmap_blit (wasteland_steam4_bits, 109, 5); break;
			case 3: 	bitmap_blit (wasteland_steam3_bits, 110, 3); break;
		}//end of case

 	 	 //right side steam #3
		 switch (random_scaled(16)) {
			case 0: 	bitmap_blit (wasteland_steam2_bits, 116, 3); break;
			case 1: 	bitmap_blit (wasteland_steam3_bits, 115, 4); break;
			case 2: 	bitmap_blit (wasteland_steam4_bits, 116, 2); break;
			case 3: 	bitmap_blit (wasteland_steam1_bits, 115, 3); break;
		}//end of case

 	 	 //right side steam #4
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_steam4_bits, 97, 5); break;
			case 1: 	bitmap_blit (wasteland_steam3_bits, 98, 4); break;
			case 2: 	bitmap_blit (wasteland_steam2_bits, 97, 5); break;
			case 3: 	bitmap_blit (wasteland_steam1_bits, 98, 3); break;
		}//end of case

	 	 //right side steam #5
		 switch (random_scaled(8)) {
			case 0: 	bitmap_blit (wasteland_steam2_bits, 122, 13); break;
			case 1: 	bitmap_blit (wasteland_steam3_bits, 121, 12); break;
			case 2: 	bitmap_blit (wasteland_steam4_bits, 122, 12); break;
			case 3: 	bitmap_blit (wasteland_steam1_bits, 121, 13); break;
		}//end of case

 	 	 //right side steam #6
		 switch (random_scaled(12)) {
			case 0: 	bitmap_blit (wasteland_steam4_bits, 126, 9); break;
			case 1: 	bitmap_blit (wasteland_steam3_bits, 126, 9); break;
			case 2: 	bitmap_blit (wasteland_steam2_bits, 125, 8); break;
			case 3: 	bitmap_blit (wasteland_steam1_bits, 125, 9); break;
		}//end of case


		 dmd_flip_low_high ();

		 dmd_show2 ();//shows a 4 color image
		task_sleep (TIME_300MS);
	dmd_alloc_pair_clean ();
}//end of func






void wasteland_effect_deff (void) {
	dmd_alloc_pair_clean();

	for (;;) {
			dmd_map_overlay ();
			dmd_clean_page_high ();
			dmd_clean_page_low ();
			dmd_draw_thin_border (dmd_low_buffer);

			font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Top - 2, "WASTELAND");

			sprintf_score(current_score);
			font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_3, sprintf_buffer);

			if (WL_TOGGLE == 0) 		{ sprintf ("15 MILLION"); font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Bot, sprintf_buffer); }
			else if (WL_TOGGLE == 1)	{ sprintf ("JACKPOT LIT"); font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Bot, sprintf_buffer); }
			else if (WL_TOGGLE == 2)	{
										sprintf ("%d JACKPOTS MADE", wasteland_jackpot_shots_made);
										font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_4, sprintf_buffer);

										if (flag_test(FLAG_IS_SUPER_JACKPOT_ACTIVATED) )	sprintf ("SUPER JACKPOT LIT");
										else 												sprintf ("SHOOT %d TO LIGHT SUPER", 5 - (wasteland_jackpot_shots_made % 5) );
										font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_5, sprintf_buffer);
			}//end of else if (WL_TOGGLE == 2)

			dmd_text_outline ();
			dmd_alloc_pair ();
			frame_draw(IMG_WASTELAND_RUNNING);
			dmd_overlay_outline ();
			dmd_show2 ();
		task_sleep (TIME_200MS);

		show_drips();

		if (++wasteland_display_counter % 10 == 0) { if (++WL_TOGGLE > 2) WL_TOGGLE = 0; } //change WL_TOGGLE once per second
	}//END OF ENDLESS LOOP
}//end of function

