/*
 * demolition man
 * wasteland.c
 * 
 * written by James Cardona
 *
 * handles the lock freezes and the trigger of multiballs
 *
 *
 * */
/* CALLSET_SECTION (wasteland, __machine3__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct

//local variables
score_t		wasteland_score;
U8			wasteland_jackpot_shots_made;
U8			wasteland_MessageCounter;
__boolean	wasteland_start_music;

//external variables
extern U8			NumBallsFrozen; //from lock_freeze_mbstart.c

//internally called function prototypes  --external found at protos.h
void wasteland_player_reset (void);
void wasteland_jackpot_effect(void);

/****************************************************************************
 * multiball definition structure
 ***************************************************************************/
struct mb_mode_ops wasteland_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB,
	.deff_starting = DEFF_WASTELAND_START_EFFECT,
	.deff_running = DEFF_WASTELAND_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms
};
//task_gid_t gid_running;
//task_gid_t gid_in_grace;



/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void wasteland_player_reset (void) {
	flag_off(FLAG_IS_WASTELAND_MB_RUNNING);
	score_zero(wasteland_score);
	wasteland_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	wasteland_start_music = FALSE;
}//end of function



CALLSET_ENTRY (wasteland, start_player) { wasteland_player_reset(); }



/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (wasteland, music_refresh)  {
	if (wasteland_start_music)				music_request (GROUND_HUMM, PRI_GAME_QUICK8);
	else 									mb_mode_music_refresh (&wasteland_mode);
}//end of function



CALLSET_ENTRY (wasteland, display_update) { mb_mode_display_update (&wasteland_mode); }



CALLSET_ENTRY (wasteland, end_ball) {
	if (flag_test(FLAG_IS_WASTELAND_MB_RUNNING)) {
		mb_mode_end_ball (&wasteland_mode);
		jackpot_reset();
		flag_off(FLAG_IS_WASTELAND_MB_RUNNING);
		if (flag_test(FLAG_IS_R_RAMP_CLAWREADY) ) 	rramp_clawready_on();
		else										rramp_clawready_off();
	}
}//end of function



//puts in grace period if set
CALLSET_ENTRY (wasteland, single_ball_play) {
	if (flag_test(FLAG_IS_WASTELAND_MB_RUNNING)) {
//		mb_mode_single_ball (&wasteland_mode);
		mb_mode_end_ball (&wasteland_mode);
		jackpot_reset();
		flag_off(FLAG_IS_WASTELAND_MB_RUNNING);
		if (flag_test(FLAG_IS_R_RAMP_CLAWREADY) ) 	rramp_clawready_on();
		else										rramp_clawready_off();
	}
}//end of function

/****************************************************************************
 * body
 *
 ***************************************************************************/
void wasteland_start(void) {
	wasteland_start_music = TRUE; //for to play the helicopter instead of the music
	flag_on(FLAG_IS_WASTELAND_MB_RUNNING);
	mb_mode_start(&wasteland_mode);
	multiball_started();//reset all MB start criteria for next time
	deff_start (DEFF_WASTELAND_START_EFFECT);
	diverter_stop();//defined in divhold2.ct

	//LIGHTS
			lamp_tristate_flash(LM_WASTELAND_MULTIBALL);
			task_sleep (TIME_2S);
			lamp_tristate_on (LM_WASTELAND_MULTIBALL);
			lamp_tristate_off (LM_FREEZE_1);
			lamp_tristate_off (LM_FREEZE_2);
			lamp_tristate_off (LM_FREEZE_3);
			lamp_tristate_off (LM_FREEZE_4);


	//SOUNDS
			U8 	wasteland_SoundCounter;
			wasteland_SoundCounter = random_scaled(2);//from kernal/random.c - pick number from 0 to 2
			if (wasteland_SoundCounter == 0)
				sound_start (ST_SPEECH, SPCH_IN_THIS_CENTURY, SL_4S, PRI_GAME_QUICK5);
			else
				sound_start (ST_SPEECH, SPCH_FEEL_GOOD_TOO, SL_4S, PRI_GAME_QUICK5);
	task_sleep (TIME_3S);
	wasteland_start_music = FALSE; //for to kill the music

	choose_random_jackpot();//randomize which jackpot shot to make
	//----------
	//serve balls
	//----------
	set_ball_count (4);  //this also works unless the number is > 2 then set_ball_count_task at serve.c breaks horribly
}//end of function



//jackpot shot
void wasteland_jackpot_made(void) {
	score_add (wasteland_score, score_table[WASTELAND_MB_SCORE]);
	score (WASTELAND_MB_SCORE);
	wasteland_jackpot_effect();//under /kernel/deff.c
}//end of function



/****************************************************************************
 * DMD display and sound effects
 ****************************************************************************/
void wasteland_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}


void wasteland_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_steel, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void wasteland_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}





void wasteland_start_effect_deff(void) {
	U16 fno;
	dmd_clean_page_high ();//
	dmd_clean_page_low ();//
	for (fno = IMG_WASTELAND_A1_START; fno <= IMG_WASTELAND_A1_END; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop

	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(IMG_WASTELAND_A2_START);
	dmd_show2 ();
	task_sleep (TIME_100MS);


	for (fno = IMG_WASTELAND_A2_START; fno <= IMG_WASTELAND_A2_END; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop

	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(IMG_WASTELAND_A3_START);
	dmd_show2 ();
	task_sleep (TIME_100MS);


	dmd_alloc_pair_clean ();// Clean both pages
	for (fno = IMG_WASTELAND_A3_START; fno <= IMG_WASTELAND_A3_END; fno += 2) {
		dmd_map_overlay ();
		dmd_clean_page_low ();
		font_render_string_center (&font_steel, DMD_MIDDLE_X + 10, DMD_BIG_CY_Bot, "WASTELAND");
		dmd_text_outline ();
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_overlay_outline ();
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
	task_sleep_sec (2);
		deff_exit ();
}//end of mode_effect_deff



void wasteland_jackpot_sounds_task(void) {
	U8 			wasteland_MessageCounter;
	wasteland_MessageCounter = random_scaled(3);
	if (++wasteland_jackpot_shots_made % 2 == 0) {
			switch (wasteland_MessageCounter) {
				case 0: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_WES, SL_2S, PRI_GAME_QUICK5); break;
				case 1: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_SLY, SL_2S, PRI_GAME_QUICK5); break;
				case 2: 	sound_start (ST_SPEECH, SPCH_DOUBLE, SL_2S, PRI_GAME_QUICK5); break;
			}//end of switch
	}//end of if
	else {
		switch (wasteland_MessageCounter) {
			case 0: 	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK5); break;
			case 1: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK5); break;
			case 2: 	sound_start (ST_SPEECH, SPCH_UHHN, SL_2S, PRI_GAME_QUICK5); break;
		}//end of switch
	}//end of else
	task_sleep (TIME_500MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK5);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_LONG, SL_2S, PRI_GAME_QUICK5);
	task_sleep (TIME_500MS);
	task_exit();
}//end of mode_effect_deff




void wasteland_jackpot_effect(void) {
	deff_start (DEFF_WASTELAND_JACKPOT_EFFECT);
}//end of FUNCTION



U8 			wasteland_MessageCounter;
void wasteland_jackpot_effect_deff(void) {
//	if (++wasteland_MessageCounter > 5) wasteland_MessageCounter = 0;
	wasteland_MessageCounter = random_scaled(6);
	dmd_alloc_pair_clean ();

	task_create_gid1 (GID_WASTELAND_JACKPOT_SOUND, wasteland_jackpot_sounds_task);

	switch (wasteland_MessageCounter) {
		default:
		case 0:
			wasteland_animation_display_effect (IMG_WASTELAND_B1_START, IMG_WASTELAND_B1_END);
			wasteland_frame_with_words_display_steel_effect (IMG_WASTELAND_B1_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 1:
			wasteland_animation_display_effect (IMG_WASTELAND_A2_START, IMG_WASTELAND_A2_END);
			wasteland_frame_with_words_display_steel_effect (IMG_WASTELAND_A2_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 2:
			wasteland_animation_display_effect (IMG_WASTELAND_A1_START, IMG_WASTELAND_A1_END);
			wasteland_frame_with_words_display_steel_effect (IMG_WASTELAND_A1_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 3:
			wasteland_animation_display_effect (IMG_FLYKICK_A_START, IMG_FLYKICK_A_END);
			wasteland_frame_with_words_display_steel_effect (IMG_FLYKICK_A_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 4:
			wasteland_animation_display_effect (IMG_WASTELAND_A3_START, IMG_WASTELAND_A3_END);
			wasteland_frame_with_words_display_steel_effect (IMG_WASTELAND_A3_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 5:
			wasteland_animation_display_effect (IMG_WASTELAND_B2_START, IMG_WASTELAND_B2_END);
			wasteland_frame_with_words_display_steel_effect (IMG_WASTELAND_B2_END, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		}//end of switch
		task_sleep_sec (2);
		deff_exit ();
}//end of mode_effect_deff




	//the image is 4 color in 2 panes, so we must increment by 2's not 1's
	U8 wasteland_effect_deff_table[] = {	0, 2, 0, 2, 4, 2, 4, 2, 0, 0,
										2, 4, 6, 8, 6, 8, 4, 2, 0, 6,
										2, 6, 8, 4, 6, 8, 2, 0, 2, 0, 4, 2 };

	void wasteland_effect_deff (void) {
		U8 wasteland_display_counter = 0;
		__boolean TOGGLE = FALSE;

		dmd_alloc_pair_clean();

		for (;;) {
				dmd_map_overlay ();
				dmd_clean_page_low ();
				dmd_draw_thin_border (dmd_low_buffer);
				font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Top, "WASTELAND");
				if (wasteland_display_counter % 10 != 0) { //draw for 9/10 and blank for 1/10
							if (TOGGLE) 	sprintf ("15 MILLION");
							else 			sprintf ("JACKPOT LIT"); }
				else 						sprintf ("");

				font_render_string_center (&font_steel, DMD_MIDDLE_X, DMD_BIG_CY_Bot, sprintf_buffer);

				dmd_text_outline ();
				dmd_alloc_pair ();
				frame_draw(IMG_FORTRESS_RUN_0 + wasteland_effect_deff_table[wasteland_display_counter]);
				dmd_overlay_outline ();
				dmd_show2 ();
			task_sleep (TIME_200MS);

			wasteland_display_counter++;
			if (wasteland_display_counter >= 30) wasteland_display_counter  = 0;
			if (wasteland_display_counter % 10 == 0) { if (TOGGLE) TOGGLE = FALSE; else TOGGLE = TRUE; }//change TOGGLE once per second
		}//END OF ENDLESS LOOP
	}//end of function

